**E-Commerce Data Analysis Project
Online Retail Dataset Analysis**

In [1]:
import numpy as np
import pandas as pd

📊 **Dataset Information
Dataset: Online Retail Dataset **

PART A: Initial Data Exploration

Task 1: Load the dataset and display basic information about its structure.

In [2]:
import kagglehub
path = kagglehub.dataset_download("vijayuv/onlineretail")

Using Colab cache for faster access to the 'onlineretail' dataset.

In [3]:
df=pd.read_csv('/kaggle/input/onlineretail/OnlineRetail.csv',encoding='ISO-8859-1')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [5]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

Task 2: Show the first 15 and last 15 records.

In [6]:
df.head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,12/1/2010 8:34,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom

In [7]:
df.tail(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,12/9/2011 12:50,1.65,12680.0,France
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,12/9/2011 12:50,1.65,12680.0,France
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,12/9/2011 12:50,3.75,12680.0,France
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,12/9/2011 12:50,3.75,12680.0,France
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,12/9/2011 12:50,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,12/9/2011 12:50,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,12/9/2011 12:50,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,12/9/2011 12:50,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

Task 3: Display a random sample of 20 transactions.

In [8]:
df.sample(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
163723,550622,22499,WOODEN UNION JACK BUNTING,12,4/19/2011 13:49,5.95,13735.0,United Kingdom
289992,562347,84596B,SMALL DOLLY MIX DESIGN ORANGE BOWL,3,8/4/2011 12:22,0.42,13263.0,United Kingdom
238248,557937,22335,HEART DECORATION PAINTED ZINC,13,6/23/2011 15:30,1.25,NaN,United Kingdom
51337,540646,17012D,ORIGAMI ROSE INCENSE/CANDLE SET,1,1/10/2011 14:32,2.51,NaN,United Kingdom
372489,569244,23142,IVORY WIRE KITCHEN ORGANISER,4,10/3/2011 9:45,10.40,13344.0,United Kingdom
250889,559051,22371,AIRLINE BAG VINTAGE TOKYO 78,1,7/5/2011 16:47,4.13,NaN,United Kingdom
109604,545655,22384,LUNCH BAG PINK POLKADOT,1,3/4/2011 13:58,1.65,14670.0,United Kingdom
471090,576618,85099F,JUMBO BAG STRAWBERRY,1,11/15/2011 17:00,4.13,NaN,United Kingdom
429576,573576,85152,HAND OVER THE CHOCOLATE SIGN,7,10/31/2011 14:09,4.13,14096.0,United Kingdom
346951,567213,20984,12 PENCILS TALL TUBE POSY,2,9/19/2011 11:04,0.29,14684.0,United Kingdom
301797,563354,22586,FELTCRAFT HAIRBAND PINK AND BLUE,1,8/15/2011 14:35,0.85,15271.0,United Kingdom
414969,572511,23284,DOORMAT KEEP CALM AND COME IN,2,10/24/2011 14:29,8.25,14895.0,United Kingdom
378229,C569636,22998,TRAVEL CARD WALLET KEEP CALM,-2,10/5/2011 12:14,0.42,12841.0,United Kingdom
130213,547418,85114A,BLACK ENCHANTED FOREST PLACEMAT,6,3/23/2011 10:25,1.65,13148.0,United Kingdom
442491,574674,22371,AIRLINE BAG VINTAGE TOKYO 78,2,11/6/2011 12:30,4.25,14404.0,United Kingdom
360774,568310,23198,PANTRY MAGNETIC SHOPPING LIST,12,9/26/2011 12:48,1.45,14911.0,EIRE
471674,576646,22556,PLASTERS IN TIN CIRCUS PARADE,12,11/16/2011 10:18,1.65,NaN,Unspecified
514240,579689,22410,MONEY BOX HOUSEKEEPING DESIGN,2,11/30/2011 14:00,1.25,14606.0,United Kingdom
157308,550201,22382,LUNCH BAG SPACEBOY DESIGN,10,4/15/2011 10:25,1.65,12769.0,Brazil
267925,560368,20726,LUNCH BAG WOODLAND,1,7/18/2011 12:25,1.65,17841.0,United Kingdom

In [9]:
df.sample(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
185895,552830,23201,JUMBO BAG ALPHABET,20,5/11/2011 13:49,1.95,15187.0,United Kingdom
434508,574048,82494L,WOODEN FRAME ANTIQUE WHITE,6,11/2/2011 13:37,2.95,13769.0,United Kingdom
528989,580730,22188,BLACK HEART CARD HOLDER,2,12/5/2011 17:28,8.29,NaN,United Kingdom
226217,556784,21056,DOCTOR'S BAG SOFT TOY,2,6/14/2011 13:15,8.95,14461.0,United Kingdom
532594,580983,23494,VINTAGE DOILY DELUXE SEWING KIT,2,12/6/2011 16:26,12.46,NaN,United Kingdom
255029,559338,22210,WOOD STAMP SET BEST WISHES,3,7/7/2011 16:30,0.83,NaN,United Kingdom
515422,579777,21993,FLORAL FOLK STATIONERY SET,2,11/30/2011 15:13,2.46,NaN,United Kingdom
464769,576181,23526,WALL ART DOG LICENCE,1,11/14/2011 11:19,5.95,15572.0,United Kingdom
336587,566395,23171,REGENCY TEA PLATE GREEN,12,9/12/2011 12:48,1.65,14952.0,United Kingdom
318523,564837,21317,GLASS SPHERE CANDLE STAND MEDIUM,2,8/30/2011 12:40,10.79,NaN,United Kingdom
68378,541864,47570B,TEA TIME TABLE CLOTH,50,1/23/2011 16:17,8.49,13798.0,United Kingdom
315640,564733,23309,SET OF 60 I LOVE LONDON CAKE CASES,2,8/28/2011 13:18,0.55,17841.0,United Kingdom
283973,561820,21916,SET 12 RETRO WHITE CHALK STICKS,1,7/29/2011 16:00,0.83,NaN,United Kingdom
190156,553183,22514,CHILDS GARDEN SPADE BLUE,6,5/15/2011 12:31,2.10,16076.0,United Kingdom
500385,578781,22979,PANTRY WASHING UP BRUSH,1,11/25/2011 11:54,1.45,15872.0,United Kingdom
367798,568908,23174,REGENCY SUGAR BOWL GREEN,4,9/29/2011 13:38,4.15,16653.0,United Kingdom
266090,560244,22090,PAPER BUNTING RETROSPOT,3,7/17/2011 12:14,2.95,16931.0,United Kingdom
82952,543277,20751,FUNKY WASHING UP GLOVES ASSORTED,4,2/6/2011 14:33,2.10,15808.0,United Kingdom
391824,570680,22080,RIBBON REEL POLKADOTS,3,10/11/2011 15:36,1.65,13969.0,United Kingdom
251906,559055,21576,LETS GO SHOPPING COTTON TOTE BAG,2,7/5/2011 17:09,1.63,NaN,United Kingdom

Task 4: Find out how many rows and columns are in the dataset.

In [10]:
df.shape

(541909, 8)

Task 5: List all column names.

In [11]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

Task 6: Check the data type of each column.

In [12]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

Task 7: Get a statistical summary of all numerical columns.

In [14]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [15]:
df.describe(include='all')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900,4070,4223,NaN,23260,NaN,NaN,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/2011 14:41,NaN,NaN,United Kingdom
freq,1114,2313,2369,NaN,1114,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,NaN,4.611114,15287.690570,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN
min,NaN,NaN,NaN,-80995.000000,NaN,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,NaN,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,NaN,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,NaN,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,NaN,38970.000000,18287.000000,NaN

In [16]:
df.describe(include='object')

,InvoiceNo,StockCode,Description,InvoiceDate,Country
count,541909,541909,540455,541909,541909
unique,25900,4070,4223,23260,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,10/31/2011 14:41,United Kingdom
freq,1114,2313,2369,1114,495478



PART B: Data Quality Assessment

Task 8: Identify which columns have missing values and how many.

In [17]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Task 9: Find out how many transactions have missing CustomerID.

In [18]:
df['CustomerID'].isna().sum()

np.int64(135080)

Task 10: Check if there are any duplicate rows in the dataset.

In [19]:
df.duplicated().sum()

np.int64(5268)

Task 11: Identify transactions where Quantity is less than or equal to zero.

In [20]:
(df['Quantity']<=0).sum()

np.int64(10624)

Task 12: Find transactions where UnitPrice is zero or negative.

In [21]:
(df['UnitPrice']<=0).sum()

np.int64(2517)

Task 13: Identify how many invoice numbers start with the letter 'C'.

In [22]:
(df['InvoiceNo'].str[0]=='C').sum()

np.int64(9288)

Task 14: Check if the Description column has any leading or trailing spaces.

In [23]:
df['Description'].str.startswith(' ').count()

np.int64(540455)

In [24]:
df['Description'].str.endswith(' ').count()

np.int64(540455)

In [25]:
df['Description'].str.startswith(' ').sum()

1271

In [26]:
df['Description'].str.endswith(' ').sum()

112626

PART C: Data Cleaning

Task 15: Remove all rows where CustomerID is missing.

In [27]:
df['CustomerID'].isna().sum()

np.int64(135080)

In [28]:
df['CustomerID'].isna().any().sum()

np.int64(1)

In [29]:
df=df.dropna(subset=['CustomerID'])

In [30]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

Task 16: For missing product descriptions, fill them with "Unknown Product".

In [31]:
df['Description']=df['Description'].fillna('Unknown Product')

/tmp/ipython-input-1916229238.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Description']=df['Description'].fillna('Unknown Product')

In [32]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

Task 17: Remove all duplicate transactions.

In [33]:
df.duplicated().sum()

np.int64(5225)

In [34]:
df=df.drop_duplicates()

In [35]:
df.duplicated().sum()

np.int64(0)

Task 18: Remove transactions where Quantity is less than or equal to zero.

In [36]:
df_clean1=df[df['Quantity']>=0]

In [37]:
df_clean1

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [38]:
(df_clean1['Quantity']<=0).sum()

np.int64(0)

In [39]:
df_clean1['Quantity'].unique()

array([    6,     8,     2,    32,     3,     4,    24,    12,    48,
          18,    20,    36,    80,    64,    10,   120,    96,    23,
           5,     1,    50,    40,   100,   192,   432,   144,   288,
          16,     9,   128,    25,    30,    28,     7,    72,   200,
         600,   480,    14,    11,    70,   252,    60,   216,   384,
          27,   108,    52,    75,   270,    42,   240,    90,   320,
          17,  1824,   204,    69,   160,  2880,  1400,    19,    39,
          56,    13,  1440,    15,   720,   156,   324,    41,   402,
         378,   150,   300,    22,    34,   408,   972,   208,  1008,
          26,  1000,  1488,   250,  1394,   400,   110,    37,    78,
          21,   272,    84,    47,  1728,    38,    53,    76,   576,
          29,  2400,   500,   180,   960,  1296,   147,   168,   256,
          54,    31,   860,  1010,  1356,  1284,   186,   114,   360,
        1930,  2000,  3114,  1300,   670,   176,   648,    62, 74215,
          89,    33,    46,   112,   456,   900,    45,   130,  2592,
         420,   800,    35,  1200,   864,   504,  1056,  1500,   280,
         407,   141,  3906,  1152,   198,   117,   125,    81,   768,
          88,    43,   700,  2160,    55,   342,   304,   640,   220,
         350,   312,   392,   330,   151,    44,   462,    66,   492,
         273,    65,    85,  1350,   428,   336,   101,   132,   227,
        2700,   222,   228,   246,   906,   756,   888,   552,   224,
         738,   608,  4300,   276,    58,    98,    51,    74,  1600,
         323,  1515,   660,   104,   264,   188,   588,   612,   152,
          49,   430,   701,   828,   540,   696,   560,   121,   512,
         291,  3186,    83,    87,    79,   109,   129,   261,   352,
         102,   348,  1900,   157,   116,   968,   684,   824,   196,
         124,   248,   410,   236,   230,   210,   448,   140,    86,
         840,   450,    93,   494,    92,  1788,   624,   744,   416,
         496,   396,   306,  1878,  1944,   666,   708,  1428,   852,
        1412,   528,   183,  1540,   672,    67,    63,    94,   255,
          57,   126,   468,  4800,   912,  1992,   136,  3000,   232,
         832,   992,   630,  1020,  2100,   162,   234,   244, 12540,
          95,   760,   139,   115,   774,  2040,  1120,    59,   490,
         388,   620,  1404,   698, 80995])

Task 19: Remove transactions where UnitPrice is less than or equal to zero.

In [40]:
df_clean2=df[df['UnitPrice']>=0]

In [41]:
df_clean2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [42]:
df_clean2['UnitPrice']

0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
541904    0.85
541905    2.10
541906    4.15
541907    4.15
541908    4.95
Name: UnitPrice, Length: 401604, dtype: float64

In [43]:
(df_clean2['UnitPrice']<=0).sum()

np.int64(40)

Task 20: Remove all cancelled transactions (invoices starting with 'C').

In [44]:
df_clean3=df[df['InvoiceNo'].str[0]!='C']

In [45]:
df_clean3

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [46]:
(df_clean3['InvoiceNo'].str[0]=='C').sum()

np.int64(0)

Task 21: Change the column name "Description" to "ProductName".

In [47]:
df=df.rename(columns={'Description':'ProductName'})

In [48]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

Task 22: Ensure the InvoiceDate column is in proper date-time format.

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  object
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      401604 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 27.6+ MB

In [50]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [51]:
df.dtypes

InvoiceNo              object
StockCode              object
ProductName            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

Task 23: Convert CustomerID to integer type.

In [52]:
df['CustomerID']=df['CustomerID'].astype(int)

In [53]:
df.dtypes

InvoiceNo              object
StockCode              object
ProductName            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object

Task 24: Reset the index after all cleaning operations.

In [54]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [55]:
df.reset_index(drop=True, inplace=True)

In [56]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 24.5+ MB

**PART D: Feature Creation**

Task 25: Create a new column called "TotalPrice" that represents the total value of each transaction.

In [58]:
df['TotalPrice']=df['Quantity']*df['UnitPrice']

In [59]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 27.6+ MB

In [61]:
df.shape

(401604, 9)

Task 26: Extract the year from InvoiceDate and store it in a new column "Year".

In [62]:
df['Year']=df['InvoiceDate'].dt.year

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
 9   Year         401604 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(1), int64(2), object(4)
memory usage: 29.1+ MB

Task 27: Extract the month from InvoiceDate and store it in a new column "Month".

In [64]:
df['Month']=df['InvoiceDate'].dt.month

In [65]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12
...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
 9   Year         401604 non-null  int32
 10  Month        401604 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(2), int64(2), object(4)
memory usage: 30.6+ MB

Task 28: Extract the day from InvoiceDate and store it in a new column "Day".

In [67]:
df['Day']=df['InvoiceDate'].dt.day

In [68]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
 9   Year         401604 non-null  int32
 10  Month        401604 non-null  int32
 11  Day          401604 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(3), int64(2), object(4)
memory usage: 32.2+ MB

Task 29: Extract the hour from InvoiceDate and store it in a new column "Hour".

In [70]:
df['Hour']=df['InvoiceDate'].dt.hour

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
 9   Year         401604 non-null  int32
 10  Month        401604 non-null  int32
 11  Day          401604 non-null  int32
 12  Hour         401604 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(4), int64(2), object(4)
memory usage: 33.7+ MB

In [72]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,8
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9,12
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9,12
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12

Task 30: Create a column "DayOfWeek" showing which day of the week the transaction occurred.

In [73]:
df['DayOfWeek']=df['InvoiceDate'].dt.day_name()

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   ProductName  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
 9   Year         401604 non-null  int32
 10  Month        401604 non-null  int32
 11  Day          401604 non-null  int32
 12  Hour         401604 non-null  int32
 13  DayOfWeek    401604 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(4), int64(2), object(5)
memory usage: 36.8+ MB

In [75]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,8,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9,12,Friday
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9,12,Friday
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12,Friday

Task 31: Create a column "Quarter" showing which quarter (Q1, Q2, Q3, Q4) the transaction belongs to.

In [76]:
df['Qurater']=df['InvoiceDate'].dt.to_period('Q')

In [77]:
df['Qurater'].unique()

<PeriodArray>
['2010Q4', '2011Q1', '2011Q2', '2011Q3', '2011Q4']
Length: 5, dtype: period[Q-DEC]

Task 32: Create a column "RevenueCategory" with three levels:

"Low" for transactions under £10
"Medium" for transactions between £10 and £100
"High" for transactions above £100

In [78]:
def revenue_category(price):
    if price < 10:
        return 'Low'
    elif price <= 100:
        return 'Medium'
    else:
        return 'High'

In [79]:
df['RevenueCategory'] = df['TotalPrice'].apply(revenue_category)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   InvoiceNo        401604 non-null  object
 1   StockCode        401604 non-null  object
 2   ProductName      401604 non-null  object
 3   Quantity         401604 non-null  int64
 4   InvoiceDate      401604 non-null  datetime64[ns]
 5   UnitPrice        401604 non-null  float64
 6   CustomerID       401604 non-null  int64
 7   Country          401604 non-null  object
 8   TotalPrice       401604 non-null  float64
 9   Year             401604 non-null  int32
 10  Month            401604 non-null  int32
 11  Day              401604 non-null  int32
 12  Hour             401604 non-null  int32
 13  DayOfWeek        401604 non-null  object
 14  Qurater          401604 non-null  period[Q-DEC]
 15  RevenueCategory  401604 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(4), int64(2), object(6), period[Q-DEC](1)
memory usage: 42.9+ MB

In [81]:
df['RevenueCategory'].unique()

array(['Medium', 'Low', 'High'], dtype=object)

Task 33: Create a column "OrderSize" with three levels:

"Small" for Quantity less than 5
"Medium" for Quantity between 5 and 20
"Large" for Quantity greater than 20

In [82]:
def ordsize(qnty):
  if qnty < 5:
    return 'Small'
  elif qnty <= 20:
    return 'Medium'
  else:
    return 'Large'

In [83]:
df['OrderSize']=df['Quantity'].apply(ordsize)

In [84]:
df['OrderSize'].unique()

array(['Medium', 'Small', 'Large'], dtype=object)

Task 34: Create a column that shows the length of each product name.

In [85]:
df['Length_product_name']=df['ProductName'].str.len()

In [86]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,19
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,35
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9,12,Friday,2011Q4,Medium,Medium,27
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9,12,Friday,2011Q4,Medium,Medium,28
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,29
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,31
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12,Friday,2011Q4,Medium,Small,29

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   InvoiceNo            401604 non-null  object
 1   StockCode            401604 non-null  object
 2   ProductName          401604 non-null  object
 3   Quantity             401604 non-null  int64
 4   InvoiceDate          401604 non-null  datetime64[ns]
 5   UnitPrice            401604 non-null  float64
 6   CustomerID           401604 non-null  int64
 7   Country              401604 non-null  object
 8   TotalPrice           401604 non-null  float64
 9   Year                 401604 non-null  int32
 10  Month                401604 non-null  int32
 11  Day                  401604 non-null  int32
 12  Hour                 401604 non-null  int32
 13  DayOfWeek            401604 non-null  object
 14  Qurater              401604 non-null  period[Q-DEC]
 15  RevenueCategory      401604 non-null  object
 16  OrderSize            401604 non-null  object
 17  Length_product_name  401604 non-null  int64
dtypes: datetime64[ns](1), float64(2), int32(4), int64(3), object(7), period[Q-DEC](1)
memory usage: 49.0+ MB

**PART E: Text Data Processing**

Task 35: Convert all product names to uppercase.

In [88]:
df['ProductName']=df['ProductName'].str.upper()

In [89]:
df['ProductName']

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
401599            PACK OF 20 SPACEBOY NAPKINS
401600           CHILDREN'S APRON DOLLY GIRL
401601          CHILDRENS CUTLERY DOLLY GIRL
401602        CHILDRENS CUTLERY CIRCUS PARADE
401603          BAKING SET 9 PIECE RETROSPOT
Name: ProductName, Length: 401604, dtype: object

Task 36: Remove any extra spaces from the Country column.

In [90]:
df['Country']=df['Country'].str.strip()

In [91]:
df['Country']

0         United Kingdom
1         United Kingdom
2         United Kingdom
3         United Kingdom
4         United Kingdom
               ...
401599            France
401600            France
401601            France
401602            France
401603            France
Name: Country, Length: 401604, dtype: object


Task 37: Find all products that contain the word "BAG" in their name.

In [92]:
product_bag=df[df['ProductName'].str.contains('BAG')]

In [93]:
product_bag

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name
38,536370,22661,CHARLOTTE BAG DOLLY GIRL DESIGN,20,2010-12-01 08:45:00,0.85,12583,France,17.0,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,31
86,536378,22386,JUMBO BAG PINK POLKADOT,10,2010-12-01 09:37:00,1.95,14688,United Kingdom,19.5,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,23
87,536378,85099C,JUMBO BAG BAROQUE BLACK WHITE,10,2010-12-01 09:37:00,1.95,14688,United Kingdom,19.5,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,30
88,536378,21033,JUMBO BAG CHARLIE AND LOLA TOYS,10,2010-12-01 09:37:00,2.95,14688,United Kingdom,29.5,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,31
89,536378,20723,STRAWBERRY CHARLOTTE BAG,10,2010-12-01 09:37:00,0.85,14688,United Kingdom,8.5,2010,12,1,9,Wednesday,2010Q4,Low,Medium,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401528,581579,23343,JUMBO BAG VINTAGE CHRISTMAS,30,2011-12-09 12:19:00,1.79,17581,United Kingdom,53.7,2011,12,9,12,Friday,2011Q4,Medium,Large,28
401529,581579,23344,JUMBO BAG 50'S CHRISTMAS,20,2011-12-09 12:19:00,1.79,17581,United Kingdom,35.8,2011,12,9,12,Friday,2011Q4,Medium,Medium,25
401530,581579,23581,JUMBO BAG PAISLEY PARK,40,2011-12-09 12:19:00,1.79,17581,United Kingdom,71.6,2011,12,9,12,Friday,2011Q4,Medium,Large,22
401557,581581,23681,LUNCH BAG RED VINTAGE DOILY,10,2011-12-09 12:20:00,1.65,17581,United Kingdom,16.5,2011,12,9,12,Friday,2011Q4,Medium,Medium,27
401560,581583,20725,LUNCH BAG RED RETROSPOT,40,2011-12-09 12:23:00,1.45,13777,United Kingdom,58.0,2011,12,9,12,Friday,2011Q4,Medium,Large,23

Task 38: Find all products whose names start with "WHITE".

In [94]:
white=df[df['ProductName'].str.startswith('WHITE')]

In [95]:
white

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,19
49,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:02:00,2.55,17850,United Kingdom,15.30,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,34
50,536373,71053,WHITE METAL LANTERN,6,2010-12-01 09:02:00,3.39,17850,United Kingdom,20.34,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,19
66,536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:32:00,2.55,17850,United Kingdom,15.30,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400927,581472,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-12-08 19:55:00,2.95,15796,United Kingdom,17.70,2011,12,8,19,Thursday,2011Q4,Medium,Medium,34
401040,581476,21479,WHITE SKULL HOT WATER BOTTLE,4,2011-12-09 08:48:00,4.25,12433,Norway,17.00,2011,12,9,8,Friday,2011Q4,Medium,Small,29
401281,581502,23210,WHITE ROCKING HORSE HAND PAINTED,12,2011-12-09 10:51:00,1.25,15910,United Kingdom,15.00,2011,12,9,10,Friday,2011Q4,Medium,Medium,32
401348,581538,21673,WHITE SPOT BLUE CERAMIC DRAWER KNOB,1,2011-12-09 11:34:00,1.45,14446,United Kingdom,1.45,2011,12,9,11,Friday,2011Q4,Low,Small,35
401407,581567,21479,WHITE SKULL HOT WATER BOTTLE,4,2011-12-09 11:56:00,4.25,16626,United Kingdom,17.00,2011,12,9,11,Friday,2011Q4,Medium,Small,29

Task 39: Find all products whose names end with "HOLDER".

In [96]:
holder=df[df['ProductName'].str.endswith('HOLDER')]

In [97]:
holder

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,25.50,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,33
49,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:02:00,2.55,17850,United Kingdom,15.30,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,34
64,536373,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 09:02:00,4.25,17850,United Kingdom,25.50,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,33
66,536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:32:00,2.55,17850,United Kingdom,15.30,2010,12,1,9,Wednesday,2010Q4,Medium,Medium,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401411,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom,-1.25,2011,12,9,11,Friday,2011Q4,Low,Small,32
401436,581571,85053,FRENCH ENAMEL CANDLEHOLDER,2,2011-12-09 12:00:00,2.10,15311,United Kingdom,4.20,2011,12,9,12,Friday,2011Q4,Low,Small,26
401520,581579,22197,POPCORN HOLDER,24,2011-12-09 12:19:00,0.85,17581,United Kingdom,20.40,2011,12,9,12,Friday,2011Q4,Medium,Large,14
401567,581585,22460,EMBOSSED GLASS TEALIGHT HOLDER,12,2011-12-09 12:31:00,1.25,15804,United Kingdom,15.00,2011,12,9,12,Friday,2011Q4,Medium,Medium,30
401571,581585,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,24,2011-12-09 12:31:00,0.85,15804,United Kingdom,20.40,2011,12,9,12,Friday,2011Q4,Medium,Large,34

Task 40: Replace "United Kingdom" with "UK" in the Country column.

Task 41: Replace "EIRE" with "Ireland" in the Country column.

In [98]:
df['Counrty']=df['Country'].astype(str)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   InvoiceNo            401604 non-null  object
 1   StockCode            401604 non-null  object
 2   ProductName          401604 non-null  object
 3   Quantity             401604 non-null  int64
 4   InvoiceDate          401604 non-null  datetime64[ns]
 5   UnitPrice            401604 non-null  float64
 6   CustomerID           401604 non-null  int64
 7   Country              401604 non-null  object
 8   TotalPrice           401604 non-null  float64
 9   Year                 401604 non-null  int32
 10  Month                401604 non-null  int32
 11  Day                  401604 non-null  int32
 12  Hour                 401604 non-null  int32
 13  DayOfWeek            401604 non-null  object
 14  Qurater              401604 non-null  period[Q-DEC]
 15  RevenueCategory      401604 non-null  object
 16  OrderSize            401604 non-null  object
 17  Length_product_name  401604 non-null  int64
 18  Counrty              401604 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(4), int64(3), object(8), period[Q-DEC](1)
memory usage: 52.1+ MB

In [100]:
df['Country']=df['Country'].replace({'United Kingdom':'UK','EIRE':'Ireland'})

In [101]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9,12,Friday,2011Q4,Medium,Medium,27,France
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9,12,Friday,2011Q4,Medium,Medium,28,France
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,31,France
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   InvoiceNo            401604 non-null  object
 1   StockCode            401604 non-null  object
 2   ProductName          401604 non-null  object
 3   Quantity             401604 non-null  int64
 4   InvoiceDate          401604 non-null  datetime64[ns]
 5   UnitPrice            401604 non-null  float64
 6   CustomerID           401604 non-null  int64
 7   Country              401604 non-null  object
 8   TotalPrice           401604 non-null  float64
 9   Year                 401604 non-null  int32
 10  Month                401604 non-null  int32
 11  Day                  401604 non-null  int32
 12  Hour                 401604 non-null  int32
 13  DayOfWeek            401604 non-null  object
 14  Qurater              401604 non-null  period[Q-DEC]
 15  RevenueCategory      401604 non-null  object
 16  OrderSize            401604 non-null  object
 17  Length_product_name  401604 non-null  int64
 18  Counrty              401604 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(4), int64(3), object(8), period[Q-DEC](1)
memory usage: 52.1+ MB

In [103]:
df['Country'].unique()

array(['UK', 'France', 'Australia', 'Netherlands', 'Germany', 'Norway',
       'Ireland', 'Switzerland', 'Spain', 'Poland', 'Portugal', 'Italy',
       'Belgium', 'Lithuania', 'Japan', 'Iceland', 'Channel Islands',
       'Denmark', 'Cyprus', 'Sweden', 'Austria', 'Israel', 'Finland',
       'Greece', 'Singapore', 'Lebanon', 'United Arab Emirates',
       'Saudi Arabia', 'Czech Republic', 'Canada', 'Unspecified',
       'Brazil', 'USA', 'European Community', 'Bahrain', 'Malta', 'RSA'],
      dtype=object)

In [104]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9,12,Friday,2011Q4,Medium,Medium,27,France
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9,12,Friday,2011Q4,Medium,Medium,28,France
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,31,France
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France

PART F: Data Selection and Filtering
**bold text**

Task 42: Select only the columns: InvoiceNo, ProductName, Quantity, UnitPrice, Country.

In [105]:
df_selected = df[['InvoiceNo', 'ProductName', 'Quantity', 'UnitPrice', 'Country']]

In [106]:
df_selected

,InvoiceNo,ProductName,Quantity,UnitPrice,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,UK
1,536365,WHITE METAL LANTERN,6,3.39,UK
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2.75,UK
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,UK
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,UK
...,...,...,...,...,...
401599,581587,PACK OF 20 SPACEBOY NAPKINS,12,0.85,France
401600,581587,CHILDREN'S APRON DOLLY GIRL,6,2.10,France
401601,581587,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,France
401602,581587,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,France
401603,581587,BAKING SET 9 PIECE RETROSPOT,3,4.95,France

Task 43: Display transactions from Germany only.

In [107]:
Germany=df[df['Country']=='Germany']

In [108]:
Germany['Counrty'].unique()

array(['Germany'], dtype=object)

In [109]:
Germany

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
1083,536527,22809,SET OF 6 T-LIGHTS SANTA,6,2010-12-01 13:04:00,2.95,12662,Germany,17.70,2010,12,1,13,Wednesday,2010Q4,Medium,Medium,23,Germany
1084,536527,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,6,2010-12-01 13:04:00,2.55,12662,Germany,15.30,2010,12,1,13,Wednesday,2010Q4,Medium,Medium,35,Germany
1085,536527,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-01 13:04:00,0.85,12662,Germany,10.20,2010,12,1,13,Wednesday,2010Q4,Medium,Medium,34,Germany
1086,536527,22242,5 HOOK HANGER MAGIC TOADSTOOL,12,2010-12-01 13:04:00,1.65,12662,Germany,19.80,2010,12,1,13,Wednesday,2010Q4,Medium,Medium,29,Germany
1087,536527,22244,3 HOOK HANGER MAGIC GARDEN,12,2010-12-01 13:04:00,1.95,12662,Germany,23.40,2010,12,1,13,Wednesday,2010Q4,Medium,Medium,26,Germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401496,581578,22993,SET OF 4 PANTRY JELLY MOULDS,12,2011-12-09 12:16:00,1.25,12713,Germany,15.00,2011,12,9,12,Friday,2011Q4,Medium,Medium,28,Germany
401497,581578,22907,PACK OF 20 NAPKINS PANTRY DESIGN,12,2011-12-09 12:16:00,0.85,12713,Germany,10.20,2011,12,9,12,Friday,2011Q4,Medium,Medium,32,Germany
401498,581578,22908,PACK OF 20 NAPKINS RED APPLES,12,2011-12-09 12:16:00,0.85,12713,Germany,10.20,2011,12,9,12,Friday,2011Q4,Medium,Medium,29,Germany
401499,581578,23215,JINGLE BELL HEART ANTIQUE SILVER,12,2011-12-09 12:16:00,2.08,12713,Germany,24.96,2011,12,9,12,Friday,2011Q4,Medium,Medium,32,Germany
401500,581578,22736,RIBBON REEL MAKING SNOWMEN,10,2011-12-09 12:16:00,1.65,12713,Germany,16.50,2011,12,9,12,Friday,2011Q4,Medium,Medium,27,Germany

Task 44: Display transactions where Quantity is greater than 50.

In [110]:
Quantity_50=df[df['Quantity']==50]

In [111]:
Quantity_50['Quantity'].unique()

array([50])

In [112]:
Quantity_50

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
147,536382,22381,TOY TIDY PINK POLKADOT,50,2010-12-01 09:45:00,1.85,16098,UK,92.5,2010,12,1,9,Wednesday,2010Q4,Medium,Large,22,United Kingdom
222,536390,22198,LARGE POPCORN HOLDER,50,2010-12-01 10:19:00,1.45,17511,UK,72.5,2010,12,1,10,Wednesday,2010Q4,Medium,Large,21,United Kingdom
1199,536532,84692,BOX OF 24 COCKTAIL PARASOLS,50,2010-12-01 13:24:00,0.42,12433,Norway,21.0,2010,12,1,13,Wednesday,2010Q4,Medium,Large,27,Norway
1370,536540,22355,CHARLOTTE BAG SUKI DESIGN,50,2010-12-01 14:05:00,0.85,14911,Ireland,42.5,2010,12,1,14,Wednesday,2010Q4,Medium,Large,25,EIRE
2843,536744,47591D,PINK FAIRY CAKE CHILDRENS APRON,50,2010-12-02 13:36:00,1.65,14466,UK,82.5,2010,12,2,13,Thursday,2010Q4,Medium,Large,31,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398516,581220,22422,TOOTHPASTE TUBE PEN,50,2011-12-08 09:39:00,0.12,13924,UK,6.0,2011,12,8,9,Thursday,2011Q4,Low,Large,19,United Kingdom
398835,581266,22438,BALLOON ART MAKE YOUR OWN FLOWERS,50,2011-12-08 11:25:00,0.39,12621,Germany,19.5,2011,12,8,11,Thursday,2011Q4,Medium,Large,33,Germany
399947,581410,23546,WRAP PAISLEY PARK,50,2011-12-08 14:14:00,0.42,13098,UK,21.0,2011,12,8,14,Thursday,2011Q4,Medium,Large,18,United Kingdom
399952,581410,23231,WRAP VINTAGE DOILY,50,2011-12-08 14:14:00,0.42,13098,UK,21.0,2011,12,8,14,Thursday,2011Q4,Medium,Large,20,United Kingdom
399953,581410,23230,WRAP ALPHABET DESIGN,50,2011-12-08 14:14:00,0.42,13098,UK,21.0,2011,12,8,14,Thursday,2011Q4,Medium,Large,20,United Kingdom

Task 45: Display transactions where UnitPrice is between £5 and £10.

In [113]:
price_range_transactions = df[(df['UnitPrice'] >= 5) & (df['UnitPrice'] <= 10)]

In [114]:
price_range_transactions['UnitPrice'].unique()

array([ 7.65,  9.95,  5.95,  7.95,  6.95,  6.75,  6.45,  8.5 ,  5.45,
        6.35,  8.95,  5.49,  7.25,  5.55,  6.6 ,  6.38,  9.89,  7.5 ,
        6.25,  5.  ,  5.76,  8.49,  5.75,  5.72,  6.7 ,  6.91,  9.16,
        8.87,  7.13,  7.06,  7.45, 10.  ,  8.15,  7.9 ,  6.98,  8.25,
        8.65,  9.87,  6.  ,  5.7 ,  7.88,  6.65,  7.05,  5.39,  5.1 ,
        9.15,  7.62,  6.78,  5.88,  9.42,  6.79,  6.42,  9.84,  6.5 ,
        6.4 ,  8.  ,  5.8 ,  7.85,  6.89,  5.32,  9.36,  9.6 ,  6.76,
        5.14,  5.08,  5.15,  5.79,  8.29,  7.46,  7.08,  5.06,  5.18,
        6.63,  9.96,  8.12,  5.64,  6.72,  9.98,  6.36,  9.13,  6.67,
        5.66,  5.35,  5.68,  5.5 ,  5.17,  6.71,  7.6 ,  7.  ,  5.13,
        9.72,  7.84])

In [115]:
price_range_transactions

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850,UK,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Small,28,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047,UK,19.90,2010,12,1,8,Wednesday,2010Q4,Medium,Small,30,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047,UK,17.85,2010,12,1,8,Wednesday,2010Q4,Medium,Small,24,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047,UK,17.85,2010,12,1,8,Wednesday,2010Q4,Medium,Small,24,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047,UK,31.80,2010,12,1,8,Wednesday,2010Q4,Medium,Small,27,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401550,581580,21351,CINAMMON & ORANGE WREATH,1,2011-12-09 12:20:00,6.75,12748,UK,6.75,2011,12,9,12,Friday,2011Q4,Low,Small,24,United Kingdom
401553,581580,79321,CHILLI LIGHTS,2,2011-12-09 12:20:00,5.75,12748,UK,11.50,2011,12,9,12,Friday,2011Q4,Medium,Small,13,United Kingdom
401573,581585,23356,LOVE HOT WATER BOTTLE,3,2011-12-09 12:31:00,5.95,15804,UK,17.85,2011,12,9,12,Friday,2011Q4,Medium,Small,21,United Kingdom
401587,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113,UK,214.80,2011,12,9,12,Friday,2011Q4,High,Large,29,United Kingdom
401588,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113,UK,70.80,2011,12,9,12,Friday,2011Q4,Medium,Medium,21,United Kingdom

Task 46: Display transactions from France with Quantity greater than 20.

In [116]:
France_transaction=df[ (df['Country']=='France') & (df['Quantity']>20)  ]

In [117]:
France_transaction['Country'].unique()

array(['France'], dtype=object)

In [118]:
France_transaction['Quantity'].unique()

array([ 24,  48,  36,  28,  25,  72, 120, 192,  30,  60, 144, 576,  96,
       108, 160,  80, 100,  64,  40, 200,  32,  50,  84, 360, 216, 240,
       168,  90, 288,  56, 150, 912,  75, 300, 250])

In [119]:
France_transaction

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583,France,90.00,2010,12,1,8,Wednesday,2010Q4,Medium,Large,25,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583,France,90.00,2010,12,1,8,Wednesday,2010Q4,Medium,Large,25,France
30,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583,France,15.60,2010,12,1,8,Wednesday,2010Q4,Medium,Large,16,France
31,536370,10002,INFLATABLE POLITICAL GLOBE,48,2010-12-01 08:45:00,0.85,12583,France,40.80,2010,12,1,8,Wednesday,2010Q4,Medium,Large,27,France
32,536370,21791,VINTAGE HEADS AND TAILS CARD GAME,24,2010-12-01 08:45:00,1.25,12583,France,30.00,2010,12,1,8,Wednesday,2010Q4,Medium,Large,34,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396280,581001,23084,RABBIT NIGHT LIGHT,24,2011-12-07 08:07:00,1.79,12583,France,42.96,2011,12,7,8,Wednesday,2011Q4,Medium,Large,18,France
396294,581001,22726,ALARM CLOCK BAKELIKE GREEN,24,2011-12-07 08:07:00,3.75,12583,France,90.00,2011,12,7,8,Wednesday,2011Q4,Medium,Large,26,France
397899,581171,22966,GINGERBREAD MAN COOKIE CUTTER,24,2011-12-07 15:02:00,1.25,12615,France,30.00,2011,12,7,15,Wednesday,2011Q4,Medium,Large,29,France
397910,581171,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,2011-12-07 15:02:00,0.29,12615,France,13.92,2011,12,7,15,Wednesday,2011Q4,Medium,Large,33,France
397917,581171,23084,RABBIT NIGHT LIGHT,24,2011-12-07 15:02:00,1.79,12615,France,42.96,2011,12,7,15,Wednesday,2011Q4,Medium,Large,18,France

Task 47: Display transactions from December 2010.

In [120]:
December_2010=df[df['InvoiceDate']>='2010-12-01']

In [121]:
December_2010['InvoiceDate'].unique()

<DatetimeArray>
['2010-12-01 08:26:00', '2010-12-01 08:28:00', '2010-12-01 08:34:00',
 '2010-12-01 08:35:00', '2010-12-01 08:45:00', '2010-12-01 09:00:00',
 '2010-12-01 09:01:00', '2010-12-01 09:02:00', '2010-12-01 09:09:00',
 '2010-12-01 09:32:00',
 ...
 '2011-12-09 12:09:00', '2011-12-09 12:16:00', '2011-12-09 12:19:00',
 '2011-12-09 12:20:00', '2011-12-09 12:21:00', '2011-12-09 12:23:00',
 '2011-12-09 12:25:00', '2011-12-09 12:31:00', '2011-12-09 12:49:00',
 '2011-12-09 12:50:00']
Length: 20460, dtype: datetime64[ns]

Task 48: Display transactions that occurred on weekends.

In [122]:
weekend_sales = df[df['DayOfWeek'].isin(['Saturday','Sunday'])]

In [123]:
weekend_sales['DayOfWeek'].unique()

array(['Sunday'], dtype=object)

In [124]:
df['DayOfWeek'].unique()

array(['Wednesday', 'Thursday', 'Friday', 'Sunday', 'Monday', 'Tuesday'],
      dtype=object)

In [125]:
weekend_sales

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
5027,537037,22114,HOT WATER BOTTLE TEA AND SYMPATHY,8,2010-12-05 10:03:00,3.95,17243,UK,31.60,2010,12,5,10,Sunday,2010Q4,Medium,Medium,33,United Kingdom
5028,537037,21485,RETROSPOT HEART HOT WATER BOTTLE,6,2010-12-05 10:03:00,4.95,17243,UK,29.70,2010,12,5,10,Sunday,2010Q4,Medium,Medium,32,United Kingdom
5029,537037,22835,HOT WATER BOTTLE I AM SO POORLY,3,2010-12-05 10:03:00,4.65,17243,UK,13.95,2010,12,5,10,Sunday,2010Q4,Medium,Small,31,United Kingdom
5030,537037,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-05 10:03:00,3.75,17243,UK,22.50,2010,12,5,10,Sunday,2010Q4,Medium,Medium,30,United Kingdom
5031,537037,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-05 10:03:00,3.75,17243,UK,22.50,2010,12,5,10,Sunday,2010Q4,Medium,Medium,35,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390291,580536,21156,RETROSPOT CHILDRENS APRON,8,2011-12-04 16:07:00,1.95,12490,France,15.60,2011,12,4,16,Sunday,2011Q4,Medium,Medium,25,France
390292,580536,21880,RED RETROSPOT TAPE,12,2011-12-04 16:07:00,0.65,12490,France,7.80,2011,12,4,16,Sunday,2011Q4,Low,Medium,18,France
390293,580536,22090,PAPER BUNTING RETROSPOT,6,2011-12-04 16:07:00,2.95,12490,France,17.70,2011,12,4,16,Sunday,2011Q4,Medium,Medium,23,France
390294,580536,22628,PICNIC BOXES SET OF 3 RETROSPOT,4,2011-12-04 16:07:00,4.95,12490,France,19.80,2011,12,4,16,Sunday,2011Q4,Medium,Small,32,France
390295,580536,POST,POSTAGE,3,2011-12-04 16:07:00,18.00,12490,France,54.00,2011,12,4,16,Sunday,2011Q4,Medium,Small,7,France

Task 49: Display the top 10 transactions by TotalPrice.

In [126]:
top10_transactions = df.sort_values(by='TotalPrice', ascending=False).head(10)

In [127]:
top10_transactions

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
401131,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446,UK,168469.60,2011,12,9,9,Friday,2011Q4,High,Large,27,United Kingdom
37511,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,UK,77183.60,2011,1,18,10,Tuesday,2011Q1,High,Large,30,United Kingdom
157405,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098,UK,38970.00,2011,6,10,15,Friday,2011Q2,High,Large,30,United Kingdom
119907,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029,UK,8142.75,2011,5,3,13,Tuesday,2011Q2,High,Small,7,United Kingdom
252000,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,2011-09-20 11:05:00,5.06,17450,UK,7144.72,2011,9,20,11,Tuesday,2011Q3,High,Large,35,United Kingdom
111014,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-04-18 13:20:00,2.10,15749,UK,6539.40,2011,4,18,13,Monday,2011Q2,High,Large,34,United Kingdom
33109,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-01-11 12:55:00,2.10,15749,UK,6539.40,2011,1,11,12,Tuesday,2011Q1,High,Large,34,United Kingdom
312033,573003,23084,RABBIT NIGHT LIGHT,2400,2011-10-27 12:11:00,2.08,14646,Netherlands,4992.00,2011,10,27,12,Thursday,2011Q4,High,Large,18,Netherlands
33107,540815,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2011-01-11 12:55:00,2.55,15749,UK,4921.50,2011,1,11,12,Tuesday,2011Q1,High,Large,34,United Kingdom
111010,550461,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2011-04-18 13:20:00,2.40,15749,UK,4632.00,2011,4,18,13,Monday,2011Q2,High,Large,34,United Kingdom

Task 50: Display the bottom 15 transactions by TotalPrice.

In [128]:
bottom15_transactions = df.sort_values(by='TotalPrice').head(15)

In [129]:
bottom15_transactions

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
401132,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446,UK,-168469.60,2011,12,9,9,Friday,2011Q4,Low,Small,27,United Kingdom
37516,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346,UK,-77183.60,2011,1,18,10,Tuesday,2011Q1,Low,Small,30,United Kingdom
157406,C556445,M,MANUAL,-1,2011-06-10 15:31:00,38970.00,15098,UK,-38970.00,2011,6,10,15,Friday,2011Q2,Low,Small,6,United Kingdom
312797,C573079,M,MANUAL,-2,2011-10-27 14:15:00,4161.06,12536,France,-8322.12,2011,10,27,14,Thursday,2011Q4,Low,Small,6,France
119809,C551685,POST,POSTAGE,-1,2011-05-03 12:51:00,8142.75,16029,UK,-8142.75,2011,5,3,12,Tuesday,2011Q2,Low,Small,7,United Kingdom
119916,C551699,M,MANUAL,-1,2011-05-03 14:12:00,6930.00,16029,UK,-6930.00,2011,5,3,14,Tuesday,2011Q2,Low,Small,6,United Kingdom
110949,C550456,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,-3114,2011-04-18 13:08:00,2.10,15749,UK,-6539.40,2011,4,18,13,Monday,2011Q2,Low,Small,34,United Kingdom
110947,C550456,85123A,WHITE HANGING HEART T-LIGHT HOLDER,-1930,2011-04-18 13:08:00,2.55,15749,UK,-4921.50,2011,4,18,13,Monday,2011Q2,Low,Small,34,United Kingdom
110945,C550456,48185,DOORMAT FAIRY CAKE,-670,2011-04-18 13:08:00,6.75,15749,UK,-4522.50,2011,4,18,13,Monday,2011Q2,Low,Small,18,United Kingdom
189323,C560372,M,MANUAL,-1,2011-07-18 12:26:00,4287.63,17448,UK,-4287.63,2011,7,18,12,Monday,2011Q3,Low,Small,6,United Kingdom
299195,C571750,M,MANUAL,-1,2011-10-19 11:16:00,3949.32,12744,Singapore,-3949.32,2011,10,19,11,Wednesday,2011Q4,Low,Small,6,Singapore
253138,C567527,23113,PANTRY CHOPPING BOARD,-756,2011-09-21 09:16:00,5.06,17450,UK,-3825.36,2011,9,21,9,Wednesday,2011Q3,Low,Small,21,United Kingdom
110948,C550456,21175,GIN + TONIC DIET METAL SIGN,-2000,2011-04-18 13:08:00,1.85,15749,UK,-3700.00,2011,4,18,13,Monday,2011Q2,Low,Small,27,United Kingdom
110946,C550456,47566B,TEA TIME PARTY BUNTING,-1300,2011-04-18 13:08:00,2.55,15749,UK,-3315.00,2011,4,18,13,Monday,2011Q2,Low,Small,22,United Kingdom
209184,C562647,M,MANUAL,-1,2011-08-08 12:56:00,3155.95,15502,UK,-3155.95,2011,8,8,12,Monday,2011Q3,Low,Small,6,United Kingdom

Task 51: Find all transactions from either UK, Germany, or France.

In [130]:
transactions_selected = df[df['Country'].isin(['UK', 'Germany', 'France'])]

In [131]:
transactions_selected['Country'].unique()

array(['UK', 'France', 'Germany'], dtype=object)

In [132]:
transactions_selected

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9,12,Friday,2011Q4,Medium,Medium,27,France
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9,12,Friday,2011Q4,Medium,Medium,28,France
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,31,France
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France

Task 52: Find transactions where TotalPrice is above the 95th percentile.

In [133]:
threshold = df['TotalPrice'].quantile(0.95)

In [134]:
high_value_transactions = df[df['TotalPrice'] > threshold]

In [135]:
high_value_transactions

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583,France,90.00,2010,12,1,8,Wednesday,2010Q4,Medium,Large,25,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583,France,90.00,2010,12,1,8,Wednesday,2010Q4,Medium,Large,25,France
34,536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND,24,2010-12-01 08:45:00,2.95,12583,France,70.80,2010,12,1,8,Wednesday,2010Q4,Medium,Large,35,France
40,536370,22900,SET 2 TEA TOWELS I LOVE LONDON,24,2010-12-01 08:45:00,2.95,12583,France,70.80,2010,12,1,8,Wednesday,2010Q4,Medium,Large,32,France
46,536371,22086,PAPER CHAIN KIT 50'S CHRISTMAS,80,2010-12-01 09:00:00,2.55,13748,UK,204.00,2010,12,1,9,Wednesday,2010Q4,High,Large,31,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401522,581579,23313,VINTAGE CHRISTMAS BUNTING,15,2011-12-09 12:19:00,4.95,17581,UK,74.25,2011,12,9,12,Friday,2011Q4,Medium,Medium,25,United Kingdom
401530,581579,23581,JUMBO BAG PAISLEY PARK,40,2011-12-09 12:19:00,1.79,17581,UK,71.60,2011,12,9,12,Friday,2011Q4,Medium,Large,22,United Kingdom
401563,581584,85038,6 CHOCOLATE LOVE HEART T-LIGHTS,48,2011-12-09 12:25:00,1.85,13777,UK,88.80,2011,12,9,12,Friday,2011Q4,Medium,Large,31,United Kingdom
401587,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113,UK,214.80,2011,12,9,12,Friday,2011Q4,High,Large,29,United Kingdom
401588,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113,UK,70.80,2011,12,9,12,Friday,2011Q4,Medium,Medium,21,United Kingdom

**PART G: Sorting Operations**

Task 53: Sort the entire dataset by InvoiceDate in ascending order.

In [136]:
df_sorted_date = df.sort_values(by='InvoiceDate', ascending=True)

In [137]:
df_sorted_date

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401591,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680,France,19.80,2011,12,9,12,Friday,2011Q4,Medium,Medium,25,France
401590,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680,France,19.80,2011,12,9,12,Friday,2011Q4,Medium,Medium,30,France
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,31,France
401595,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680,France,15.00,2011,12,9,12,Friday,2011Q4,Medium,Small,26,France
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France

Task 54: Sort the dataset by TotalPrice in descending order.

In [138]:
df.isna().sum()

InvoiceNo              0
StockCode              0
ProductName            0
Quantity               0
InvoiceDate            0
UnitPrice              0
CustomerID             0
Country                0
TotalPrice             0
Year                   0
Month                  0
Day                    0
Hour                   0
DayOfWeek              0
Qurater                0
RevenueCategory        0
OrderSize              0
Length_product_name    0
Counrty                0
dtype: int64

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   InvoiceNo            401604 non-null  object
 1   StockCode            401604 non-null  object
 2   ProductName          401604 non-null  object
 3   Quantity             401604 non-null  int64
 4   InvoiceDate          401604 non-null  datetime64[ns]
 5   UnitPrice            401604 non-null  float64
 6   CustomerID           401604 non-null  int64
 7   Country              401604 non-null  object
 8   TotalPrice           401604 non-null  float64
 9   Year                 401604 non-null  int32
 10  Month                401604 non-null  int32
 11  Day                  401604 non-null  int32
 12  Hour                 401604 non-null  int32
 13  DayOfWeek            401604 non-null  object
 14  Qurater              401604 non-null  period[Q-DEC]
 15  RevenueCategory      401604 non-null  object
 16  OrderSize            401604 non-null  object
 17  Length_product_name  401604 non-null  int64
 18  Counrty              401604 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(4), int64(3), object(8), period[Q-DEC](1)
memory usage: 52.1+ MB

In [140]:
df_sorted_price = df.sort_values(by='TotalPrice', ascending=False)

In [141]:
df_sorted_price

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
401131,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446,UK,168469.60,2011,12,9,9,Friday,2011Q4,High,Large,27,United Kingdom
37511,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,UK,77183.60,2011,1,18,10,Tuesday,2011Q1,High,Large,30,United Kingdom
157405,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098,UK,38970.00,2011,6,10,15,Friday,2011Q2,High,Large,30,United Kingdom
119907,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029,UK,8142.75,2011,5,3,13,Tuesday,2011Q2,High,Small,7,United Kingdom
252000,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,2011-09-20 11:05:00,5.06,17450,UK,7144.72,2011,9,20,11,Tuesday,2011Q3,High,Large,35,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119809,C551685,POST,POSTAGE,-1,2011-05-03 12:51:00,8142.75,16029,UK,-8142.75,2011,5,3,12,Tuesday,2011Q2,Low,Small,7,United Kingdom
312797,C573079,M,MANUAL,-2,2011-10-27 14:15:00,4161.06,12536,France,-8322.12,2011,10,27,14,Thursday,2011Q4,Low,Small,6,France
157406,C556445,M,MANUAL,-1,2011-06-10 15:31:00,38970.00,15098,UK,-38970.00,2011,6,10,15,Friday,2011Q2,Low,Small,6,United Kingdom
37516,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346,UK,-77183.60,2011,1,18,10,Tuesday,2011Q1,Low,Small,30,United Kingdom
401132,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446,UK,-168469.60,2011,12,9,9,Friday,2011Q4,Low,Small,27,United Kingdom

Task 55: Sort by Country (ascending) and then by TotalPrice (descending).

In [142]:
df_sorted = df.sort_values(by=['Country', 'TotalPrice'], ascending=[True, False])

In [143]:
df_sorted

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
348972,576394,23084,RABBIT NIGHT LIGHT,960,2011-11-15 10:32:00,1.79,12415,Australia,1718.40,2011,11,15,10,Tuesday,2011Q4,High,Large,18,Australia
217754,563614,22940,FELTCRAFT CHRISTMAS FAIRY,336,2011-08-18 08:51:00,3.75,12415,Australia,1260.00,2011,8,18,8,Thursday,2011Q3,High,Large,25,Australia
70370,545475,21217,RED RETROSPOT ROUND CAKE TINS,120,2011-03-03 10:59:00,8.95,12415,Australia,1074.00,2011,3,3,10,Thursday,2011Q1,High,Large,29,Australia
217824,563614,23314,VINTAGE CHRISTMAS TABLECLOTH,100,2011-08-18 08:51:00,10.39,12415,Australia,1039.00,2011,8,18,8,Thursday,2011Q3,High,Large,28,Australia
28351,540267,22720,SET OF 3 CAKE TINS PANTRY DESIGN,240,2011-01-06 11:12:00,4.25,12415,Australia,1020.00,2011,1,6,11,Thursday,2011Q1,High,Large,33,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199826,561661,47343A,FUSCHIA FLOWER PURSE WITH BEADS,1,2011-07-28 16:21:00,0.83,12743,Unspecified,0.83,2011,7,28,16,Thursday,2011Q3,Low,Small,31,Unspecified
199707,561658,47574A,ENGLISH ROSE SCENTED HANGING FLOWER,1,2011-07-28 16:06:00,0.75,12743,Unspecified,0.75,2011,7,28,16,Thursday,2011Q3,Low,Small,35,Unspecified
199771,561658,47348A,FUSCHIA VOILE POINTY SHOE DEC,1,2011-07-28 16:06:00,0.39,12743,Unspecified,0.39,2011,7,28,16,Thursday,2011Q3,Low,Small,29,Unspecified
199821,561661,22396,MAGNETS PACK OF 4 RETRO PHOTO,1,2011-07-28 16:21:00,0.39,12743,Unspecified,0.39,2011,7,28,16,Thursday,2011Q3,Low,Small,29,Unspecified
199796,561661,79063C,"RETRO PILL BOX KEY CHAIN,THE KING",1,2011-07-28 16:21:00,0.19,12743,Unspecified,0.19,2011,7,28,16,Thursday,2011Q3,Low,Small,33,Unspecified

Task 56: Find the 20 highest-value transactions.

In [144]:
top20_transactions = df.sort_values(by='TotalPrice', ascending=False).head(20)

In [145]:
top20_transactions

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
401131,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446,UK,168469.60,2011,12,9,9,Friday,2011Q4,High,Large,27,United Kingdom
37511,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,UK,77183.60,2011,1,18,10,Tuesday,2011Q1,High,Large,30,United Kingdom
157405,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098,UK,38970.00,2011,6,10,15,Friday,2011Q2,High,Large,30,United Kingdom
119907,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029,UK,8142.75,2011,5,3,13,Tuesday,2011Q2,High,Small,7,United Kingdom
252000,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,2011-09-20 11:05:00,5.06,17450,UK,7144.72,2011,9,20,11,Tuesday,2011Q3,High,Large,35,United Kingdom
111014,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-04-18 13:20:00,2.10,15749,UK,6539.40,2011,4,18,13,Monday,2011Q2,High,Large,34,United Kingdom
33109,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-01-11 12:55:00,2.10,15749,UK,6539.40,2011,1,11,12,Tuesday,2011Q1,High,Large,34,United Kingdom
312033,573003,23084,RABBIT NIGHT LIGHT,2400,2011-10-27 12:11:00,2.08,14646,Netherlands,4992.00,2011,10,27,12,Thursday,2011Q4,High,Large,18,Netherlands
33107,540815,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2011-01-11 12:55:00,2.55,15749,UK,4921.50,2011,1,11,12,Tuesday,2011Q1,High,Large,34,United Kingdom
111010,550461,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2011-04-18 13:20:00,2.40,15749,UK,4632.00,2011,4,18,13,Monday,2011Q2,High,Large,34,United Kingdom
33169,540818,48185,DOORMAT FAIRY CAKE,670,2011-01-11 12:57:00,6.75,15749,UK,4522.50,2011,1,11,12,Tuesday,2011Q1,High,Large,18,United Kingdom
173829,558526,23173,REGENCY TEAPOT ROSES,540,2011-06-30 11:01:00,8.15,17949,UK,4401.00,2011,6,30,11,Thursday,2011Q2,High,Large,21,United Kingdom
111012,550461,48185,DOORMAT FAIRY CAKE,670,2011-04-18 13:20:00,6.35,15749,UK,4254.50,2011,4,18,13,Monday,2011Q2,High,Large,18,United Kingdom
206823,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,2011-08-04 18:06:00,1.45,12931,UK,4176.00,2011,8,4,18,Thursday,2011Q3,High,Large,29,United Kingdom
312773,573077,M,MANUAL,1,2011-10-27 14:13:00,4161.06,12536,France,4161.06,2011,10,27,14,Thursday,2011Q4,High,Small,6,France
312798,573080,M,MANUAL,1,2011-10-27 14:20:00,4161.06,12536,France,4161.06,2011,10,27,14,Thursday,2011Q4,High,Small,6,France
32539,540689,22470,HEART OF WICKER LARGE,1284,2011-01-11 08:43:00,3.21,17450,UK,4121.64,2011,1,11,8,Tuesday,2011Q1,High,Large,21,United Kingdom
299197,571751,M,MANUAL,1,2011-10-19 11:18:00,3949.32,12744,Singapore,3949.32,2011,10,19,11,Wednesday,2011Q4,High,Small,6,Singapore
396953,581115,22413,METAL SIGN TAKE IT OR LEAVE IT,1404,2011-12-07 12:20:00,2.75,15195,UK,3861.00,2011,12,7,12,Wednesday,2011Q4,High,Large,31,United Kingdom
10678,537659,21623,VINTAGE UNION JACK MEMOBOARD,600,2010-12-07 16:43:00,6.38,18102,UK,3828.00,2010,12,7,16,Tuesday,2010Q4,High,Large,28,United Kingdom

Task 57: Find the 20 lowest-value transactions (excluding returns).

In [146]:
df_non_returns = df[~df['InvoiceNo'].str.startswith('C')]

In [147]:
lowest20_transactions = df_non_returns.nsmallest(20, 'TotalPrice')

In [148]:
lowest20_transactions

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty
6842,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647,Germany,0.0,2010,12,5,14,Sunday,2010Q4,Low,Small,28,Germany
22619,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,2010-12-16 14:36:00,0.0,16560,UK,0.0,2010,12,16,14,Thursday,2010Q4,Low,Small,28,United Kingdom
25551,539722,22423,REGENCY CAKESTAND 3 TIER,10,2010-12-21 13:45:00,0.0,14911,Ireland,0.0,2010,12,21,13,Tuesday,2010Q4,Low,Medium,24,EIRE
29374,540372,22090,PAPER BUNTING RETROSPOT,24,2011-01-06 16:41:00,0.0,13081,UK,0.0,2011,1,6,16,Thursday,2011Q1,Low,Large,23,United Kingdom
29376,540372,22553,PLASTERS IN TIN SKULLS,24,2011-01-06 16:41:00,0.0,13081,UK,0.0,2011,1,6,16,Thursday,2011Q1,Low,Large,22,United Kingdom
34903,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,2011-01-13 15:10:00,0.0,15107,UK,0.0,2011,1,13,15,Thursday,2011Q1,Low,Small,29,United Kingdom
54482,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2011-02-10 13:08:00,0.0,17560,UK,0.0,2011,2,10,13,Thursday,2011Q1,Low,Medium,28,United Kingdom
86760,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,2011-03-23 10:25:00,0.0,13239,UK,0.0,2011,3,23,10,Wednesday,2011Q1,Low,Large,35,United Kingdom
93947,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,2011-03-30 12:45:00,0.0,13113,UK,0.0,2011,3,30,12,Wednesday,2011Q1,Low,Medium,34,United Kingdom
98634,548871,22162,HEART GARLAND RUSTIC PADDED,2,2011-04-04 14:42:00,0.0,14410,UK,0.0,2011,4,4,14,Monday,2011Q2,Low,Small,27,United Kingdom
108583,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,2011-04-14 18:57:00,0.0,12457,Switzerland,0.0,2011,4,14,18,Thursday,2011Q2,Low,Small,34,Switzerland
130286,553000,47566,PARTY BUNTING,4,2011-05-12 15:21:00,0.0,17667,UK,0.0,2011,5,12,15,Thursday,2011Q2,Low,Small,13,United Kingdom
138864,554037,22619,SET OF 6 SOLDIER SKITTLES,80,2011-05-20 14:13:00,0.0,12415,Australia,0.0,2011,5,20,14,Friday,2011Q2,Low,Large,25,Australia
197297,561284,22167,OVAL WALL MIRROR DIAMANTE,1,2011-07-26 12:24:00,0.0,16818,UK,0.0,2011,7,26,12,Tuesday,2011Q3,Low,Small,27,United Kingdom
199859,561669,22960,JAM MAKING SET WITH JARS,11,2011-07-28 17:09:00,0.0,12507,Spain,0.0,2011,7,28,17,Thursday,2011Q3,Low,Medium,24,Spain
202393,561916,M,MANUAL,1,2011-08-01 11:44:00,0.0,15581,UK,0.0,2011,8,1,11,Monday,2011Q3,Low,Small,6,United Kingdom
211834,562973,23157,SET OF 6 NATIVITY MAGNETS,240,2011-08-11 11:42:00,0.0,14911,Ireland,0.0,2011,8,11,11,Thursday,2011Q3,Low,Large,26,EIRE
226959,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,2011-08-26 14:19:00,0.0,14646,Netherlands,0.0,2011,8,26,14,Friday,2011Q3,Low,Large,32,Netherlands
226960,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,2011-08-26 14:19:00,0.0,14646,Netherlands,0.0,2011,8,26,14,Friday,2011Q3,Low,Large,35,Netherlands
226961,564651,22955,36 FOIL STAR CAKE CASES,144,2011-08-26 14:19:00,0.0,14646,Netherlands,0.0,2011,8,26,14,Friday,2011Q3,Low,Large,24,Netherlands

**PART H: Aggregation and Summary Statistics**

Task 58: Calculate the total revenue generated across all transactions.

In [149]:
total_revenue = df['TotalPrice'].sum()

In [150]:
total_revenue

np.float64(8278519.4240000015)

Task 59: Calculate the average transaction value.

In [151]:
Average=df['TotalPrice'].mean()

In [152]:
Average

np.float64(20.613637872132752)

Task 60: Find the maximum and minimum transaction values.

In [153]:
Max = df['TotalPrice'].max()

In [154]:
Max

168469.6

In [155]:
Min = df['TotalPrice'].min()

In [156]:
Min

-168469.6

Task 61: Calculate the total number of unique customers.

In [157]:
unique_customer=df['CustomerID'].nunique()

In [158]:
unique_customer

4372

Task 62: Calculate the total number of unique products sold.

In [159]:
df['InvoiceNo'].nunique()

22190

In [160]:
product_sold=df['StockCode'].nunique()

In [161]:
product_sold

3684

Task 63: Find out how many unique countries are represented in the data.

In [162]:
unique_countries=df['Country'].nunique()

In [163]:
unique_countries

37

Task 64: Calculate the average number of items per transaction.

In [164]:
items_per_transaction = df.groupby('InvoiceNo')['Quantity'].sum().mean()

In [165]:
items_per_transaction

np.float64(220.498017124831)

Task 65: Find which product appears most frequently in transactions.

In [166]:
most_frequent_product = df['ProductName'].value_counts()

In [167]:
most_frequent_product

ProductName
WHITE HANGING HEART T-LIGHT HOLDER     2058
REGENCY CAKESTAND 3 TIER               1894
JUMBO BAG RED RETROSPOT                1659
PARTY BUNTING                          1409
ASSORTED COLOUR BIRD ORNAMENT          1405
                                       ...
LETTER "W" BLING KEY RING                 1
CROCHET LILAC/RED BEAR KEYRING            1
MIDNIGHT BLUE CRYSTAL DROP EARRINGS       1
BLACK VINT ART DEC CRYSTAL BRACELET       1
WHITE STONE/CRYSTAL EARRINGS              1
Name: count, Length: 3896, dtype: int64

**PART I: Country-wise Analysis**

Task 66: Calculate total revenue for each country.

In [168]:
Country_revenue = df.groupby('Country')['TotalPrice'].sum()

In [169]:
Country_revenue

Country
Australia                137009.770
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20076.390
Cyprus                    12858.760
Czech Republic              707.720
Denmark                   18768.140
European Community         1291.750
Finland                   22326.740
France                   196626.050
Germany                  221509.470
Greece                     4710.520
Iceland                    4310.000
Ireland                  250001.780
Israel                     6988.400
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal                  28995.760
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54756.030
Sweden                    36585.410
Switzerland               55739.400
UK                      6747156.154
USA                        1730.920
United Arab Emirates       1902.280
Unspecified                2660.770
Name: TotalPrice, dtype: float64

Task 67: Find the top 10 countries by total revenue.

In [170]:
top10_country = df.groupby('Country')['TotalPrice'].sum()

In [171]:
top10_country.sort_values(ascending=False).head(10)

Country
UK             6747156.154
Netherlands     284661.540
Ireland         250001.780
Germany         221509.470
France          196626.050
Australia       137009.770
Switzerland      55739.400
Spain            54756.030
Belgium          40910.960
Sweden           36585.410
Name: TotalPrice, dtype: float64

Task 68: Calculate the number of transactions per country.

In [172]:
Country_trans = df.groupby('Country')['InvoiceNo'].nunique()

In [173]:
Country_trans

Country
Australia                  69
Austria                    19
Bahrain                     2
Belgium                   119
Brazil                      1
Canada                      6
Channel Islands            33
Cyprus                     20
Czech Republic              5
Denmark                    21
European Community          5
Finland                    48
France                    458
Germany                   603
Greece                      6
Iceland                     7
Ireland                   319
Israel                      6
Italy                      55
Japan                      28
Lebanon                     1
Lithuania                   4
Malta                      10
Netherlands               101
Norway                     40
Poland                     24
Portugal                   70
RSA                         1
Saudi Arabia                2
Singapore                  10
Spain                     105
Sweden                     46
Switzerland                71
UK                      19857
USA                         7
United Arab Emirates        3
Unspecified                 8
Name: InvoiceNo, dtype: int64

Task 69: Calculate the average transaction value for each country.

In [174]:
country_avg_trans= df.groupby(['Country', 'InvoiceNo'])['TotalPrice'].sum().groupby('Country').mean()

In [175]:
country_avg_trans

Country
Australia               1985.648841
Austria                  534.437895
Bahrain                  274.200000
Belgium                  343.789580
Brazil                  1143.600000
Canada                   611.063333
Channel Islands          608.375455
Cyprus                   642.938000
Czech Republic           141.544000
Denmark                  893.720952
European Community       258.350000
Finland                  465.140417
France                   429.314520
Germany                  367.345721
Greece                   785.086667
Iceland                  615.714286
Ireland                  783.704639
Israel                  1164.733333
Italy                    307.100182
Japan                   1262.165000
Lebanon                 1693.880000
Lithuania                415.265000
Malta                    250.547000
Netherlands             2818.431089
Norway                   879.086500
Poland                   300.547500
Portugal                 414.225143
RSA                     1002.310000
Saudi Arabia              65.585000
Singapore                912.039000
Spain                    521.486000
Sweden                   795.335000
Switzerland              785.061972
UK                       339.787287
USA                      247.274286
United Arab Emirates     634.093333
Unspecified              332.596250
Name: TotalPrice, dtype: float64

Task 70: Find which country has the highest average order value.

In [176]:
country_avg_trans.sort_values(ascending=False).head(1)

Country
Netherlands    2818.431089
Name: TotalPrice, dtype: float64

Task 71: Calculate the total quantity of products sold to each country.

In [177]:
df.groupby('Country')['Quantity'].sum()

Country
Australia                 83643
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9473
Cyprus                     6296
Czech Republic              592
Denmark                    8188
European Community          497
Finland                   10666
France                   109806
Germany                  117341
Greece                     1556
Iceland                    2458
Ireland                  136187
Israel                     3987
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16017
RSA                         352
Saudi Arabia                 75
Singapore                  5234
Spain                     26817
Sweden                    35632
Switzerland               29778
UK                      3994870
USA                        1034
United Arab Emirates        982
Unspecified                1785
Name: Quantity, dtype: int64

Task 72: Find the country with the most unique customers.

In [178]:
uni_cust = df.groupby('Country')['CustomerID'].nunique().idxmax()

In [179]:
uni_cust

'UK'

**PART J: Time-based Analysis**

Task 73: Calculate total revenue for each month.

In [180]:
month_revenue = df.groupby(df['InvoiceDate'].dt.to_period('M'))['TotalPrice'].sum()

In [181]:
month_revenue

InvoiceDate
2010-12     552372.860
2011-01     473731.900
2011-02     435534.070
2011-03     578576.210
2011-04     425222.671
2011-05     647011.670
2011-06     606862.520
2011-07     573112.321
2011-08     615078.090
2011-09     929356.232
2011-10     973306.380
2011-11    1126815.070
2011-12     341539.430
Freq: M, Name: TotalPrice, dtype: float64

Task 74: Find which month had the highest sales.

In [182]:
highest_month = df.groupby(df['InvoiceDate'].dt.month_name())['TotalPrice'].sum().idxmax()

In [183]:
highest_month

'November'

Task 75: Calculate revenue for each quarter.

In [184]:
quarter_revenue = df.groupby(df['InvoiceDate'].dt.to_period('Q'))['TotalPrice'].sum()

In [185]:
quarter_revenue

InvoiceDate
2010Q4     552372.860
2011Q1    1487842.180
2011Q2    1679096.861
2011Q3    2117546.643
2011Q4    2441660.880
Freq: Q-DEC, Name: TotalPrice, dtype: float64

Task 76: Calculate the number of transactions per day of the week.

In [186]:
no_of_transaction_per_week = df.groupby(df['InvoiceDate'].dt.day_name())['InvoiceNo'].nunique()

In [187]:
no_of_transaction_per_week

InvoiceDate
Friday       3356
Monday       3512
Sunday       2342
Thursday     4978
Tuesday      3892
Wednesday    4110
Name: InvoiceNo, dtype: int64


Task 77: Find which day of the week has the highest average revenue.

In [188]:
highest_avg_revenue = df.groupby(df['InvoiceDate'].dt.day_name()).apply(lambda x: x.groupby('InvoiceNo')['TotalPrice'].sum().mean()).idxmax()

In [189]:
highest_avg_revenue

'Tuesday'

Task 78: Calculate hourly sales patterns (revenue by hour of day).

In [190]:
hourly_sales = df.groupby(df['InvoiceDate'].dt.hour)['TotalPrice'].sum()

In [191]:
hourly_sales

InvoiceDate
6        -497.350
7       31009.320
8      279985.430
9      654904.951
10    1148692.881
11    1053658.480
12    1332247.730
13    1118155.480
14     945058.221
15     896326.790
16     445930.100
17     212373.801
18     100525.120
19      44228.380
20      15920.090
Name: TotalPrice, dtype: float64

Task 79: Compare sales between 2010 and 2011.

In [192]:
sales_2010_2011 = df.groupby(df['InvoiceDate'].dt.year)['TotalPrice'].sum()

In [193]:
sales_2010_2011

InvoiceDate
2010     552372.860
2011    7726146.564
Name: TotalPrice, dtype: float64

Task 80: Calculate month-over-month revenue growth rate.

In [194]:
month_over_month_revenue = df.groupby(df['InvoiceDate'].dt.to_period('M'))['TotalPrice'].sum().pct_change() * 100

In [195]:
month_over_month_revenue

InvoiceDate
2010-12          NaN
2011-01   -14.236934
2011-02    -8.063175
2011-03    32.842928
2011-04   -26.505331
2011-05    52.158319
2011-06    -6.205321
2011-07    -5.561424
2011-08     7.322434
2011-09    51.095649
2011-10     4.729096
2011-11    15.771878
2011-12   -69.689842
Freq: M, Name: TotalPrice, dtype: float64

**PART K: Customer Analysis**

Task 81: Calculate total spending for each customer.

In [196]:
total_spending = df.groupby('CustomerID')['TotalPrice'].sum()

In [197]:
total_spending

CustomerID
12346       0.00
12347    4310.00
12348    1797.24
12349    1757.55
12350     334.40
          ...
18280     180.60
18281      80.82
18282     176.60
18283    2045.53
18287    1837.28
Name: TotalPrice, Length: 4372, dtype: float64

Task 82: Find the top 20 customers by total spending.

In [198]:
total_spending.sort_values( ascending=False).head(20)

CustomerID
14646    279489.02
18102    256438.49
17450    187322.17
14911    132458.73
12415    123725.45
14156    113214.59
17511     88125.38
16684     65892.08
13694     62690.54
15311     59284.19
13089     57322.13
14096     57120.91
15061     54228.74
16029     53168.69
17949     52750.84
15769     51823.72
14298     50862.44
14088     50415.49
17841     39869.05
13798     36352.87
Name: TotalPrice, dtype: float64

Task 83: Calculate the number of transactions per customer.

In [199]:
transactions_per_customer = df.groupby('CustomerID')['InvoiceNo'].nunique()

In [200]:
transactions_per_customer

CustomerID
12346     2
12347     7
12348     4
12349     1
12350     1
         ..
18280     1
18281     1
18282     3
18283    16
18287     3
Name: InvoiceNo, Length: 4372, dtype: int64

Task 84: Find the average order value for each customer.

In [201]:
avg_order = df.groupby('CustomerID').apply(lambda x: x.groupby('InvoiceNo')['TotalPrice'].sum().mean())

/tmp/ipython-input-1913150147.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  avg_order = df.groupby('CustomerID').apply(lambda x: x.groupby('InvoiceNo')['TotalPrice'].sum().mean())

In [202]:
avg_order

CustomerID
12346       0.000000
12347     615.714286
12348     449.310000
12349    1757.550000
12350     334.400000
            ...
18280     180.600000
18281      80.820000
18282      58.866667
18283     127.845625
18287     612.426667
Length: 4372, dtype: float64

Task 85: Identify customers who have made only one purchase.

In [203]:
one_time_customers = df.groupby('CustomerID')['InvoiceNo'].nunique().loc[lambda x: x == 1]

In [204]:
one_time_customers

CustomerID
12349    1
12350    1
12353    1
12354    1
12355    1
        ..
18256    1
18262    1
18278    1
18280    1
18281    1
Name: InvoiceNo, Length: 1313, dtype: int64

Task 86: Find customers who spent more than £10,000 in total.

In [205]:
big_spenders = df.groupby('CustomerID')['TotalPrice'].sum().loc[lambda x: x > 10000]

In [206]:
big_spenders

CustomerID
12409     11056.93
12415    123725.45
12433     13375.87
12471     18705.52
12477     13117.01
           ...
17841     39869.05
17857     26763.34
17865     10158.54
17949     52750.84
18102    256438.49
Name: TotalPrice, Length: 97, dtype: float64

Task 87: Calculate the average number of days between purchases for each customer.

In [207]:
avg_days_between = df.groupby('CustomerID')['InvoiceDate'].apply(lambda x: x.sort_values().diff().dt.days.mean())

In [208]:
avg_days_between

CustomerID
12346    0.000000
12347    2.000000
12348    9.400000
12349    0.000000
12350    0.000000
           ...
18280    0.000000
18281    0.000000
18282    9.833333
18283    0.454167
18287    2.275362
Name: InvoiceDate, Length: 4372, dtype: float64

**PART L: Product Analysis**

Task 88: Find the top 20 products by revenue.

In [209]:
top20_products_revenue = df.groupby('ProductName')['TotalPrice'].sum().sort_values(ascending=False).head(20)

In [210]:
top20_products_revenue

ProductName
REGENCY CAKESTAND 3 TIER              132567.70
WHITE HANGING HEART T-LIGHT HOLDER     93767.80
JUMBO BAG RED RETROSPOT                83056.52
PARTY BUNTING                          67628.43
POSTAGE                                66710.24
ASSORTED COLOUR BIRD ORNAMENT          56331.91
RABBIT NIGHT LIGHT                     51042.84
CHILLI LIGHTS                          45915.41
PAPER CHAIN KIT 50'S CHRISTMAS         41423.78
PICNIC BASKET WICKER 60 PIECES         39619.50
BLACK RECORD COVER FRAME               38990.63
JUMBO BAG PINK POLKADOT                36437.78
SPOTTY BUNTING                         35026.74
DOORMAT KEEP CALM AND COME IN          34279.60
WOOD BLACK BOARD ANT WHITE FINISH      34243.76
SET OF 3 CAKE TINS PANTRY DESIGN       32573.15
JAM MAKING SET WITH JARS               31611.72
JUMBO BAG STRAWBERRY                   30120.83
HEART OF WICKER LARGE                  28290.15
VICTORIAN GLASS HANGING T-LIGHT        28111.71
Name: TotalPrice, dtype: float64

Task 89: Find the top 20 products by quantity sold.

In [211]:
top20_products_quantity = df.groupby('ProductName')['Quantity'].sum().sort_values(ascending=False).head(20)

In [212]:
top20_products_quantity

ProductName
WORLD WAR 2 GLIDERS ASSTD DESIGNS     53119
JUMBO BAG RED RETROSPOT               44963
ASSORTED COLOUR BIRD ORNAMENT         35215
WHITE HANGING HEART T-LIGHT HOLDER    34128
PACK OF 72 RETROSPOT CAKE CASES       33386
POPCORN HOLDER                        30492
RABBIT NIGHT LIGHT                    27045
MINI PAINT SET VINTAGE                25880
PACK OF 12 LONDON TISSUES             25305
PACK OF 60 PINK PAISLEY CAKE CASES    24129
BROCADE RING PURSE                    22924
VICTORIAN GLASS HANGING T-LIGHT       21955
ASSORTED COLOURS SILK FAN             21132
RED  HARMONICA IN BOX                 20882
JUMBO BAG PINK POLKADOT               19692
SMALL POPCORN HOLDER                  18197
60 TEATIME FAIRY CAKE CASES           17514
LUNCH BAG RED RETROSPOT               17024
HEART OF WICKER SMALL                 16633
JUMBO BAG STRAWBERRY                  16521
Name: Quantity, dtype: int64

Task 90: Calculate the average price for each product.

In [213]:
avg_price_per_product = df.groupby('ProductName')['UnitPrice'].mean()

In [214]:
avg_price_per_product

ProductName
 4 PURPLE FLOCK DINNER CANDLES       2.312162
 50'S CHRISTMAS GIFT BAG LARGE       1.248091
 DOLLY GIRL BEAKER                   1.243796
 I LOVE LONDON MINI BACKPACK         4.138406
 I LOVE LONDON MINI RUCKSACK         4.150000
                                      ...
ZINC T-LIGHT HOLDER STARS SMALL      0.836888
ZINC TOP  2 DOOR WOODEN SHELF       16.768182
ZINC WILLIE WINKIE  CANDLE STICK     0.872344
ZINC WIRE KITCHEN ORGANISER          7.175000
ZINC WIRE SWEETHEART LETTER TRAY     3.454000
Name: UnitPrice, Length: 3896, dtype: float64

Task 91: Find products that have been sold to more than 10 different countries.

In [215]:
products_10plus_countries = df.groupby('ProductName')['Country'].nunique().loc[lambda x: x > 10]

In [216]:
products_10plus_countries

ProductName
 DOLLY GIRL BEAKER                     11
 SPACEBOY BABY GIFT SET                13
10 COLOUR SPACEBOY PEN                 12
12 PENCIL SMALL TUBE WOODLAND          11
12 PENCILS SMALL TUBE RED RETROSPOT    11
                                       ..
WRAP PAISLEY PARK                      14
WRAP RED APPLES                        14
WRAP RED VINTAGE DOILY                 12
ZINC FOLKART SLEIGH BELLS              11
ZINC METAL HEART DECORATION            11
Name: Country, Length: 496, dtype: int64

Task 92: Identify the most expensive and cheapest products.

In [217]:
df.loc[df['UnitPrice'].idxmax(), 'ProductName'], df.loc[df['UnitPrice'].idxmin(), 'ProductName']

('MANUAL', 'ROUND CAKE TIN VINTAGE GREEN')

In [218]:
df['UnitPrice'].max(), df['UnitPrice'].min()

(38970.0, 0.0)

**PART M: Advanced Grouping**

Task 93: Calculate total revenue by Country and Year.

In [219]:
df.groupby([df['Country'], df['InvoiceDate'].dt.year])['TotalPrice'].sum()

Country               InvoiceDate
Australia             2010               937.600
                      2011            136072.170
Austria               2010               257.040
                      2011              9897.280
Bahrain               2011               548.400
Belgium               2010              1809.910
                      2011             39101.050
Brazil                2011              1143.600
Canada                2011              3666.380
Channel Islands       2010               363.530
                      2011             19712.860
Cyprus                2010              1587.070
                      2011             11271.690
Czech Republic        2011               707.720
Denmark               2010              1281.500
                      2011             17486.640
European Community    2011              1291.750
Finland               2010               892.800
                      2011             21433.940
France                2010              9575.360
                      2011            187050.690
Germany               2010             14527.440
                      2011            206982.030
Greece                2011              4710.520
Iceland               2010               711.790
                      2011              3598.210
Ireland               2010              7825.570
                      2011            242176.210
Israel                2010              -227.440
                      2011              7215.840
Italy                 2010               794.500
                      2011             16096.010
Japan                 2010              7705.070
                      2011             27635.550
Lebanon               2011              1693.880
Lithuania             2010              1661.060
Malta                 2011              2505.470
Netherlands           2010              8784.480
                      2011            275877.060
Norway                2010              3787.120
                      2011             31376.340
Poland                2010               248.160
                      2011              6964.980
Portugal              2010              2380.120
                      2011             26615.640
RSA                   2011              1002.310
Saudi Arabia          2011               131.170
Singapore             2011              9120.390
Spain                 2010              1843.730
                      2011             52912.300
Sweden                2010              2646.300
                      2011             33939.110
Switzerland           2010              1304.920
                      2011             54434.480
UK                    2010            481675.230
                      2011           6265480.924
USA                   2011              1730.920
United Arab Emirates  2011              1902.280
Unspecified           2011              2660.770
Name: TotalPrice, dtype: float64

Task 94: Calculate average transaction value by Country and Quarter.

In [220]:
df.groupby(['Country', df['InvoiceDate'].dt.to_period('Q')]).apply(lambda x: x.groupby('InvoiceNo')['TotalPrice'].sum().mean())

/tmp/ipython-input-1282084867.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(['Country', df['InvoiceDate'].dt.to_period('Q')]).apply(lambda x: x.groupby('InvoiceNo')['TotalPrice'].sum().mean())

Country               InvoiceDate
Australia             2010Q4          234.400000
                      2011Q1         2142.130000
                      2011Q2         2794.762857
                      2011Q3         1614.425000
                      2011Q4         1996.376667
                                        ...
USA                   2011Q4          224.495000
United Arab Emirates  2011Q1          889.240000
                      2011Q3          506.520000
Unspecified           2011Q2          445.853333
                      2011Q3          264.642000
Length: 140, dtype: float64

Task 95: Find the number of transactions by Country and Month.

In [221]:
df.groupby(['Country', df['InvoiceDate'].dt.to_period('M')])['InvoiceNo'].nunique()

Country      InvoiceDate
Australia    2010-12        4
             2011-01        9
             2011-02        6
             2011-03        4
             2011-04        4
                           ..
Unspecified  2011-04        1
             2011-05        1
             2011-06        1
             2011-07        3
             2011-08        2
Name: InvoiceNo, Length: 298, dtype: int64

Task 96: Calculate total revenue by Day of Week and Hour

In [222]:
df.groupby([df['InvoiceDate'].dt.day_name(), df['InvoiceDate'].dt.hour])['TotalPrice'].sum()

InvoiceDate  InvoiceDate
Friday       7               17234.990
             8               52224.830
             9              122614.841
             10             175018.010
             11             164575.010
                               ...
Wednesday    15             156167.450
             16              76756.930
             17              16866.610
             19               2893.400
             20              13031.500
Name: TotalPrice, Length: 74, dtype: float64

Task 97: For each country, calculate the sum, mean, maximum, and minimum TotalPrice.

In [223]:
df.groupby('Country')['TotalPrice'].agg(['sum', 'mean', 'max', 'min'])

                              sum        mean        max        min
Country
Australia              137009.770  108.910787    1718.40    -425.00
Austria                 10154.320   25.322494     360.00     -21.25
Bahrain                   548.400   32.258824     120.00      11.60
Belgium                 40910.960   19.773301     165.00     -19.95
Brazil                   1143.600   35.737500     175.20      15.00
Canada                   3666.380   24.280662     550.94       2.50
Channel Islands         20076.390   26.520991     408.00    -293.00
Cyprus                  12858.760   21.045434     320.69    -320.69
Czech Republic            707.720   23.590667      70.80     -35.76
Denmark                 18768.140   48.247147     428.40     -59.80
European Community       1291.750   21.176230      60.00      -8.50
Finland                 22326.740   32.124806     551.20     -80.00
France                 196626.050   23.200714    4161.06   -8322.12
Germany                221509.470   23.365978     876.00    -599.50
Greece                   4710.520   32.263836     175.20     -50.00
Iceland                  4310.000   23.681319     249.60       5.04
Ireland                250001.780   33.445054    2365.20   -1687.17
Israel                   6988.400   28.293117     350.40    -136.00
Italy                   16890.510   21.034259     300.00     -89.55
Japan                   35340.620   98.716816    3794.40   -1591.20
Lebanon                  1693.880   37.641778     153.00      10.20
Lithuania                1661.060   47.458857     122.40      13.20
Malta                    2505.470   19.728110     455.00    -130.00
Netherlands            284661.540  120.059696    4992.00    -266.40
Norway                  35163.460   32.378877     700.00    -376.50
Poland                   7213.140   21.152903     120.00     -39.80
Portugal                28995.760   19.711598    1241.98   -1241.98
RSA                      1002.310   17.281207      38.25       0.00
Saudi Arabia              131.170   13.117000      19.80     -14.75
Singapore                9120.390   39.827031    3949.32   -3949.32
Spain                   54756.030   21.659822    1350.00   -1715.85
Sweden                  36585.410   79.360976    1188.00   -1188.00
Switzerland             55739.400   29.696004     360.00    -179.00
UK                    6747156.154   18.914008  168469.60 -168469.60
USA                      1730.920    5.948179      81.36     -74.88
United Arab Emirates     1902.280   27.974706     153.00       3.48
Unspecified              2660.770   11.040539      69.36       0.19

Task 98: For each customer, calculate their total spending, number of orders, and average order value.

In [224]:
df.groupby('CustomerID').apply(lambda x: pd.Series({
    'TotalSpending': x['TotalPrice'].sum(),
    'NumOrders': x['InvoiceNo'].nunique(),
    'AvgOrderValue': x.groupby('InvoiceNo')['TotalPrice'].sum().mean()
}))

/tmp/ipython-input-482105581.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('CustomerID').apply(lambda x: pd.Series({

            TotalSpending  NumOrders  AvgOrderValue
CustomerID
12346                0.00        2.0       0.000000
12347             4310.00        7.0     615.714286
12348             1797.24        4.0     449.310000
12349             1757.55        1.0    1757.550000
12350              334.40        1.0     334.400000
...                   ...        ...            ...
18280              180.60        1.0     180.600000
18281               80.82        1.0      80.820000
18282              176.60        3.0      58.866667
18283             2045.53       16.0     127.845625
18287             1837.28        3.0     612.426667

[4372 rows x 3 columns]

Task 99: For each product, calculate total quantity sold and total revenue generated.

In [225]:
df.groupby('ProductName').agg(TotalQuantity=('Quantity','sum'), TotalRevenue=('TotalPrice','sum'))

                                  TotalQuantity  TotalRevenue
ProductName
 4 PURPLE FLOCK DINNER CANDLES              138        265.66
 50'S CHRISTMAS GIFT BAG LARGE             1883       2269.75
 DOLLY GIRL BEAKER                         2387       2745.75
 I LOVE LONDON MINI BACKPACK                359       1449.85
 I LOVE LONDON MINI RUCKSACK                  1          4.15
...                                         ...           ...
ZINC T-LIGHT HOLDER STARS SMALL            4850       3843.46
ZINC TOP  2 DOOR WOODEN SHELF                 5         92.75
ZINC WILLIE WINKIE  CANDLE STICK           2594       2165.90
ZINC WIRE KITCHEN ORGANISER                  25        156.80
ZINC WIRE SWEETHEART LETTER TRAY             80        253.24

[3896 rows x 2 columns]

**PART N: Creating Summary Reports**

Task 100: Create a summary table showing monthly sales for each country (countries as rows, months as columns).

In [226]:
monthly_sales_country = df.pivot_table(
    index='Country',
    columns=df['InvoiceDate'].dt.to_period('M'),
    values='TotalPrice',
    aggfunc='sum',
    fill_value=0
)

In [227]:
monthly_sales_country

InvoiceDate,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12
Country,,,,,,,,,,,,,
Australia,937.60,9017.71,14627.47,17055.29,333.400,13628.51,25164.77,4767.570,22489.20,5031.730,17150.53,6805.99,0.00
Austria,257.04,0.00,518.36,1708.12,680.780,1249.43,-24.20,1191.950,1516.08,0.000,1043.78,1329.78,683.20
Bahrain,0.00,0.00,0.00,0.00,0.000,548.40,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Belgium,1809.91,1154.05,2161.32,3333.58,1954.150,2727.00,4273.17,2473.620,3536.12,4197.820,5651.38,6229.41,1409.43
Brazil,0.00,0.00,0.00,0.00,1143.600,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Canada,0.00,0.00,0.00,140.54,0.000,534.24,1171.46,1768.580,51.56,0.000,0.00,0.00,0.00
Channel Islands,363.53,645.08,1784.71,3509.33,293.000,903.79,2060.03,0.000,4882.63,1321.650,2623.32,1495.17,194.15
Cyprus,1587.07,547.50,4013.55,938.39,-35.800,0.00,1109.32,0.000,0.00,196.350,4153.97,439.66,-91.25
Czech Republic,0.00,0.00,549.26,0.00,-57.510,0.00,0.00,0.000,0.00,0.000,277.48,-61.51,0.00
Denmark,1281.50,0.00,399.22,3978.99,0.000,515.70,3261.15,376.240,78.60,4570.160,1438.11,2699.57,168.90
European Community,0.00,0.00,0.00,0.00,191.400,0.00,423.55,676.800,0.00,0.000,0.00,0.00,0.00
Finland,892.80,889.02,205.16,5924.62,1626.810,0.00,329.56,2996.730,1371.55,1105.450,2804.12,2950.24,1230.68
France,9575.36,17503.07,8438.91,14512.30,4195.210,17518.68,15722.43,9888.990,13789.26,23198.870,25017.64,30216.50,7048.83
Germany,14527.44,16421.43,8969.24,14170.02,11963.370,25554.85,13053.27,15721.660,19023.65,17708.560,30604.27,25987.01,7804.70
Greece,0.00,2661.24,0.00,387.31,609.740,0.00,0.00,371.240,0.00,0.000,0.00,0.00,680.99
Iceland,711.79,475.39,0.00,0.00,636.250,0.00,382.52,0.000,584.91,0.000,1294.32,0.00,224.82
Ireland,7825.57,21671.52,7536.92,18270.28,7570.500,15889.74,19822.79,40823.150,10771.45,40427.840,23292.62,29123.03,6976.37
Israel,-227.44,0.00,779.10,0.00,0.000,0.00,0.00,1430.750,4873.81,0.000,132.18,0.00,0.00
Italy,794.50,2361.36,251.50,1778.91,737.830,587.45,162.27,147.100,1934.80,279.800,3410.79,4243.75,200.45
Japan,7705.07,-109.80,5780.81,-73.66,4871.830,1351.45,1607.04,3854.400,-49.79,112.080,1948.04,8460.08,-116.93
Lebanon,0.00,1693.88,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Lithuania,1661.06,0.00,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Malta,0.00,0.00,0.00,0.00,0.000,0.00,850.41,0.000,1103.25,0.000,0.00,582.62,-30.81
Netherlands,8784.48,26611.16,22932.11,22416.49,2976.560,29185.88,26843.09,26.020,39655.81,26937.260,40708.65,25856.01,11728.02
Norway,3787.12,0.00,630.90,304.68,0.000,0.00,5886.86,890.070,1984.46,8678.940,3687.23,6527.50,2785.70
Poland,248.16,613.22,604.05,303.39,705.840,1522.37,264.74,678.450,401.80,529.250,0.00,1341.87,0.00
Portugal,2380.12,3998.11,1213.90,2660.85,1687.750,587.83,879.51,2287.850,1206.40,1433.220,5254.97,2603.30,2801.95
RSA,0.00,0.00,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.000,1002.31,0.00,0.00
Saudi Arabia,0.00,0.00,145.92,-14.75,0.000,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Singapore,0.00,2053.07,0.00,0.00,2118.740,0.00,0.00,3949.320,0.00,0.000,999.26,0.00,0.00
Spain,1843.73,7178.54,2093.70,5326.65,1785.650,3257.60,3332.44,7574.020,3325.91,5163.740,5078.65,8523.97,271.43
Sweden,2646.30,3446.32,509.50,4540.58,809.100,2664.98,832.00,6802.090,1380.46,4575.210,5766.16,2612.71,0.00
Switzerland,1304.92,4231.23,2642.67,1870.23,1822.190,3567.21,7882.20,3540.650,4882.19,8254.960,7623.99,8116.96,0.00
UK,481675.23,350668.80,347856.55,455534.07,375919.231,524363.88,471386.36,460082.891,475752.95,774620.302,781610.92,950731.45,296953.52
USA,0.00,0.00,0.00,0.00,383.950,0.00,0.00,0.000,0.00,0.000,731.69,0.00,615.28
United Arab Emirates,0.00,0.00,889.24,0.00,0.000,0.00,0.00,0.000,0.00,1013.040,0.00,0.00,0.00
Unspecified,0.00,0.00,0.00,0.00,299.100,852.68,185.78,792.180,531.03,0.000,0.00,0.00,0.00

Task 101: Create a summary showing average quantity purchased by country and quarter.

In [228]:
avg_qty_country_quarter = df.pivot_table(
    index='Country',
    columns=df['InvoiceDate'].dt.to_period('Q'),
    values='Quantity',
    aggfunc='mean',
    fill_value=0
)

In [229]:
avg_qty_country_quarter

InvoiceDate               2010Q4      2011Q1      2011Q2     2011Q3     2011Q4
Country
Australia              13.058824   75.097561   81.433657  50.929907  72.993711
Austria                 0.333333   33.948718    9.886076   9.531469  10.351145
Bahrain                 0.000000    0.000000   15.294118   0.000000   0.000000
Belgium                18.473684   10.566474   10.421471  11.146771  11.079805
Brazil                  0.000000    0.000000   11.125000   0.000000   0.000000
Canada                  0.000000    8.800000   27.517241  13.000000   0.000000
Channel Islands         4.705882   14.705357    9.086614  13.422330  11.912568
Cyprus                 11.170732   15.108597    7.183673  33.000000   6.418605
Czech Republic          0.000000   23.066667  -19.500000   0.000000  21.923077
Denmark                22.700000   28.282051   15.296000  26.560976  20.658537
European Community      0.000000    0.000000    5.062500  11.551724   0.000000
Finland                73.764706   14.393305   16.875000  13.932584  12.424390
France                 11.339408   14.004245   13.719253  12.754209  12.309619
Germany                11.898936   11.602024   13.501041  12.262023  12.295755
Greece                  0.000000   15.092593    8.451613   9.720000   6.555556
Iceland                10.290323   10.862069   16.166667  12.590909  14.965517
Ireland                13.419890   20.602041   17.048551  21.110970  15.562363
Israel                -28.000000   17.875000    0.000000  18.489899   3.096774
Italy                   7.146341    8.877934   16.741379   9.819672   9.880759
Japan                  62.969231   26.150442  142.465753  47.941176  95.089286
Lebanon                 0.000000    8.577778    0.000000   0.000000   0.000000
Lithuania              18.628571    0.000000    0.000000   0.000000   0.000000
Malta                   0.000000    0.000000    8.489362   6.614035   7.304348
Netherlands            94.597222   84.737274   73.468085  86.615672  91.271186
Norway                 24.367347    5.923077   12.102410  17.626506  19.731383
Poland                 17.500000   11.353846    9.807018   9.050000  12.608108
Portugal                7.875000   14.546075    7.966825  16.336585   9.003115
RSA                     0.000000    0.000000    0.000000   0.000000   6.068966
Saudi Arabia            0.000000    7.500000    0.000000   0.000000   0.000000
Singapore               0.000000   19.482143   22.322581  28.800000  16.638889
Spain                  11.560000   10.512337   10.334204  11.425185   9.967422
Sweden                137.555556  103.722892   39.366667  88.280303  62.891473
Switzerland            14.571429   15.838006   19.145205  14.395695  15.421933
UK                     10.466664   11.220338   11.551039  12.526922  10.187889
USA                     0.000000    0.000000    6.227273   0.000000   3.334572
United Arab Emirates    0.000000   16.533333    0.000000  12.789474   0.000000
Unspecified             0.000000    0.000000   14.083333   4.562130   0.000000

Task 102: Create a table showing the count of transactions in each RevenueCategory by Country.

In [230]:
transactions_by_category = df.pivot_table(
    index='Country',
    columns='RevenueCategory',
    values='InvoiceNo',
    aggfunc='nunique',
    fill_value=0
)

In [231]:
transactions_by_category

RevenueCategory       High    Low  Medium
Country
Australia               27     28      49
Austria                  6     12      17
Bahrain                  1      0       2
Belgium                 10     90      98
Brazil                   1      0       1
Canada                   2      4       4
Channel Islands          7     16      22
Cyprus                   9     11      13
Czech Republic           0      3       2
Denmark                  7     12      17
European Community       0      2       4
Finland                 27     24      40
France                  73    308     378
Germany                116    400     446
Greece                   2      5       5
Iceland                  3      5       7
Ireland                 77    198     246
Israel                   3      6       4
Italy                    8     35      36
Japan                   11     14      12
Lebanon                  1      0       1
Lithuania                1      0       4
Malta                    2      7       5
Netherlands             64     34      79
Norway                  16     24      32
Poland                   2     16      19
Portugal                18     45      51
RSA                      0      1       1
Saudi Arabia             0      2       1
Singapore                6      7       4
Spain                   33     69      84
Sweden                  18     21      32
Switzerland             28     55      46
UK                    3529  12978   15262
USA                      0      5       5
United Arab Emirates     1      1       3
Unspecified              0      4       8

**PART O: Data Transformation**

Task 103: Add a column to each row showing what percentage of the monthly total revenue that transaction represents.

In [232]:
df['MonthlyRevenuePct'] = df['TotalPrice'] / df.groupby(df['InvoiceDate'].dt.to_period('M'))['TotalPrice'].transform('sum') * 100

In [233]:

df['MonthlyRevenuePct']

0         0.002770
1         0.003682
2         0.003983
3         0.003682
4         0.003682
            ...
401599    0.002986
401600    0.003689
401601    0.004860
401602    0.004860
401603    0.004348
Name: MonthlyRevenuePct, Length: 401604, dtype: float64

In [234]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom,0.002770
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom,0.003682
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003983
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom,0.003682
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,12,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,12,9,12,Friday,2011Q4,Medium,Medium,27,France,0.002986
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,12,9,12,Friday,2011Q4,Medium,Medium,28,France,0.003689
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France,0.004860
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,12,9,12,Friday,2011Q4,Medium,Small,31,France,0.004860
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,12,9,12,Friday,2011Q4,Medium,Small,29,France,0.004348

Task 104: Add a column showing each customer's ranking based on their total spending.

In [235]:
df['CustomerRank'] = df.groupby('CustomerID')['TotalPrice'].transform('sum').rank(ascending=False, method='dense')

In [236]:
df['CustomerRank']

0          240.0
1          240.0
2          240.0
3          240.0
4          240.0
           ...
401599    1796.0
401600    1796.0
401601    1796.0
401602    1796.0
401603    1796.0
Name: CustomerRank, Length: 401604, dtype: float64

In [237]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,...,Day,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct,CustomerRank
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,...,1,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom,0.002770,240.0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,1,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom,0.003682,240.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,...,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003983,240.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,1,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom,0.003682,240.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,1,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003682,240.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,...,9,12,Friday,2011Q4,Medium,Medium,27,France,0.002986,1796.0
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,...,9,12,Friday,2011Q4,Medium,Medium,28,France,0.003689,1796.0
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,9,12,Friday,2011Q4,Medium,Small,29,France,0.004860,1796.0
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,9,12,Friday,2011Q4,Medium,Small,31,France,0.004860,1796.0
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,...,9,12,Friday,2011Q4,Medium,Small,29,France,0.004348,1796.0

Task 105: Add a column showing the cumulative revenue over time.

In [238]:
df['CumulativeRevenue'] = df.sort_values('InvoiceDate')['TotalPrice'].cumsum()

In [239]:
df['CumulativeRevenue']

0         1.530000e+01
1         3.564000e+01
2         5.764000e+01
3         7.798000e+01
4         9.832000e+01
              ...
401599    8.278333e+06
401600    8.278323e+06
401601    8.278287e+06
401602    8.278490e+06
401603    8.278519e+06
Name: CumulativeRevenue, Length: 401604, dtype: float64

In [240]:
df

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,...,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct,CustomerRank,CumulativeRevenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,...,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom,0.002770,240.0,1.530000e+01
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom,0.003682,240.0,3.564000e+01
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,...,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003983,240.0,5.764000e+01
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom,0.003682,240.0,7.798000e+01
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003682,240.0,9.832000e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,...,12,Friday,2011Q4,Medium,Medium,27,France,0.002986,1796.0,8.278333e+06
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,...,12,Friday,2011Q4,Medium,Medium,28,France,0.003689,1796.0,8.278323e+06
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,12,Friday,2011Q4,Medium,Small,29,France,0.004860,1796.0,8.278287e+06
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,12,Friday,2011Q4,Medium,Small,31,France,0.004860,1796.0,8.278490e+06
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,...,12,Friday,2011Q4,Medium,Small,29,France,0.004348,1796.0,8.278519e+06

**PART P: Combining Analysis**

Task 106: Split the dataset into two parts: 2010 data and 2011 data. Then combine them back together vertically.

In [241]:
df_combined = pd.concat([df[df['InvoiceDate'].dt.year == 2010], df[df['InvoiceDate'].dt.year == 2011]], ignore_index=True)

In [242]:
df_combined

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,...,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct,CustomerRank,CumulativeRevenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,...,8,Wednesday,2010Q4,Medium,Medium,34,United Kingdom,0.002770,240.0,1.530000e+01
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8,Wednesday,2010Q4,Medium,Medium,19,United Kingdom,0.003682,240.0,3.564000e+01
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,...,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003983,240.0,5.764000e+01
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8,Wednesday,2010Q4,Medium,Medium,35,United Kingdom,0.003682,240.0,7.798000e+01
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003682,240.0,9.832000e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,...,12,Friday,2011Q4,Medium,Medium,27,France,0.002986,1796.0,8.278333e+06
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,...,12,Friday,2011Q4,Medium,Medium,28,France,0.003689,1796.0,8.278323e+06
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,12,Friday,2011Q4,Medium,Small,29,France,0.004860,1796.0,8.278287e+06
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,12,Friday,2011Q4,Medium,Small,31,France,0.004860,1796.0,8.278490e+06
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,...,12,Friday,2011Q4,Medium,Small,29,France,0.004348,1796.0,8.278519e+06

Task 107: Create separate datasets for UK and non-UK transactions. Combine them back horizontally with appropriate labeling.

In [243]:
df_combined_horizontal = pd.concat([
    df[df['Country'] == 'UK'].reset_index(drop=True),
    df[df['Country'] != 'UK'].reset_index(drop=True)
], axis=1)

In [244]:
df_combined_horizontal

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,...,Hour,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct,CustomerRank,CumulativeRevenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,...,8.0,Wednesday,2010Q4,Medium,Large,25.0,France,0.016293,146.0,1337.01
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8.0,Wednesday,2010Q4,Medium,Large,25.0,France,0.016293,146.0,1247.01
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,...,8.0,Wednesday,2010Q4,Medium,Medium,26.0,France,0.008147,146.0,1157.01
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8.0,Wednesday,2010Q4,Medium,Medium,31.0,France,0.001847,146.0,1112.01
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,8.0,Wednesday,2010Q4,Medium,Large,16.0,France,0.002824,146.0,1101.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356723,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804,UK,23.40,2011,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356724,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113,UK,23.60,2011,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356725,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113,UK,30.00,2011,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356726,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113,UK,214.80,2011,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356727,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113,UK,70.80,2011,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**PART Q: External Data Integration**

Task 108: Create a new dataset with customer information (make up data):

CustomerID, CustomerName, MembershipLevel (Bronze/Silver/Gold), JoinDate

In [245]:
import pandas as pd
customer_data = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104, 105],
    'CustomerName': ['Alice','Bob','Charlie','David','Eva'],
    'MembershipLevel': ['Bronze','Silver','Gold','Silver','Gold'],
    'JoinDate': pd.to_datetime(['2020-01-15','2020-03-10','2020-05-20','2020-07-01','2020-09-12'])
})

Task 109: Combine this customer dataset with your sales data to show customer names and membership levels in transactions.

In [246]:
df_with_customers = df.merge(customer_data, on='CustomerID', how='left')

In [247]:
df_with_customers

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,...,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct,CustomerRank,CumulativeRevenue,CustomerName,MembershipLevel,JoinDate
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,...,Medium,Medium,34,United Kingdom,0.002770,240.0,1.530000e+01,NaN,NaN,NaT
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,Medium,Medium,19,United Kingdom,0.003682,240.0,3.564000e+01,NaN,NaN,NaT
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,...,Medium,Medium,30,United Kingdom,0.003983,240.0,5.764000e+01,NaN,NaN,NaT
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,Medium,Medium,35,United Kingdom,0.003682,240.0,7.798000e+01,NaN,NaN,NaT
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,Medium,Medium,30,United Kingdom,0.003682,240.0,9.832000e+01,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,...,Medium,Medium,27,France,0.002986,1796.0,8.278333e+06,NaN,NaN,NaT
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,...,Medium,Medium,28,France,0.003689,1796.0,8.278323e+06,NaN,NaN,NaT
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,Medium,Small,29,France,0.004860,1796.0,8.278287e+06,NaN,NaN,NaT
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,Medium,Small,31,France,0.004860,1796.0,8.278490e+06,NaN,NaN,NaT
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,...,Medium,Small,29,France,0.004348,1796.0,8.278519e+06,NaN,NaN,NaT

Task 110: Create a product categories dataset (make up data):

StockCode, Category (e.g., Home, Kitchen, Gift, etc.)

In [248]:
product_categories = pd.DataFrame({
    'StockCode': ['10001', '10002', '10003', '10004', '10005'],
    'Category': ['Home', 'Kitchen', 'Gift', 'Stationery', 'Electronics']
})

In [249]:
product_categories

  StockCode     Category
0     10001         Home
1     10002      Kitchen
2     10003         Gift
3     10004   Stationery
4     10005  Electronics

Task 111: Combine the sales data with product categories to analyze which categories generate the most revenue.

In [250]:
df_with_categories = df.merge(product_categories, on='StockCode', how='left')

In [251]:
df_with_categories

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,...,DayOfWeek,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct,CustomerRank,CumulativeRevenue,Category
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,...,Wednesday,2010Q4,Medium,Medium,34,United Kingdom,0.002770,240.0,1.530000e+01,NaN
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,Wednesday,2010Q4,Medium,Medium,19,United Kingdom,0.003682,240.0,3.564000e+01,NaN
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,...,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003983,240.0,5.764000e+01,NaN
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,Wednesday,2010Q4,Medium,Medium,35,United Kingdom,0.003682,240.0,7.798000e+01,NaN
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,Wednesday,2010Q4,Medium,Medium,30,United Kingdom,0.003682,240.0,9.832000e+01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,...,Friday,2011Q4,Medium,Medium,27,France,0.002986,1796.0,8.278333e+06,NaN
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,...,Friday,2011Q4,Medium,Medium,28,France,0.003689,1796.0,8.278323e+06,NaN
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,Friday,2011Q4,Medium,Small,29,France,0.004860,1796.0,8.278287e+06,NaN
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,Friday,2011Q4,Medium,Small,31,France,0.004860,1796.0,8.278490e+06,NaN
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,...,Friday,2011Q4,Medium,Small,29,France,0.004348,1796.0,8.278519e+06,NaN

In [252]:
df_with_categories['Category'].unique()

array([nan, 'Kitchen'], dtype=object)

Task 112: Perform an analysis that shows total revenue by MembershipLevel.

In [253]:
revenue_by_membership = df_with_customers.groupby('MembershipLevel')['TotalPrice'].sum()

In [254]:
revenue_by_membership

Series([], Name: TotalPrice, dtype: float64)

Task 113: Show which product categories are most popular in each country.

In [255]:
popular_categories = df_with_categories.groupby(['Country', 'Category'])['Quantity'].sum().groupby(level=0).idxmax()

In [256]:
popular_categories

Country
France              (France, Kitchen)
Germany            (Germany, Kitchen)
Ireland            (Ireland, Kitchen)
Japan                (Japan, Kitchen)
Spain                (Spain, Kitchen)
Switzerland    (Switzerland, Kitchen)
UK                      (UK, Kitchen)
Name: Quantity, dtype: object

**PART R: NumPy Operations**

Task 114: Extract Quantity and UnitPrice as arrays and perform element-wise multiplication.

In [257]:
total_array = df[['Quantity', 'UnitPrice']].to_numpy().prod(axis=1)

In [258]:
total_array

array([15.3 , 20.34, 22.  , ..., 16.6 , 16.6 , 14.85])

Task 115: Create an array of 1000 random transaction IDs.

In [259]:
import numpy as np
random_transaction_ids = np.random.randint(100000, 999999, size=1000)

In [260]:
random_transaction_ids

array([802411, 681288, 586471, 632777, 763365, 149138, 972650, 789615,
       101442, 913415, 624514, 525151, 844722, 252305, 790598, 957538,
       407586, 775441, 501297, 933413, 890770, 920487, 684684, 961365,
       469558, 671675, 711915, 789403, 908579, 974013, 377619, 519294,
       275012, 882403, 101583, 698233, 179680, 341061, 340100, 851062,
       199282, 222500, 641429, 121053, 783602, 673384, 303098, 143253,
       730642, 123969, 869277, 311776, 819151, 950037, 445839, 312966,
       407039, 784147, 423949, 747267, 220491, 103242, 545560, 727117,
       458964, 580138, 157690, 978793, 118315, 629914, 899748, 452071,
       598649, 497991, 179971, 368034, 476116, 843344, 751429, 784928,
       941080, 392759, 397851, 554370, 203083, 942319, 846065, 317630,
       336847, 463850, 417749, 468205, 439055, 643246, 482065, 568888,
       980116, 681894, 262552, 315070, 833037, 645297, 257950, 751443,
       535211, 120973, 540709, 244408, 552191, 600865, 207089, 828623,
       714451, 710470, 875792, 873532, 127803, 607094, 588608, 274715,
       321271, 806862, 848567, 882403, 623727, 867453, 575503, 126068,
       471245, 412235, 414256, 915276, 745921, 623784, 758763, 908161,
       815339, 661690, 755850, 385724, 499023, 694486, 467332, 533023,
       732463, 243300, 872204, 142101, 270270, 480287, 269787, 585051,
       941614, 170613, 787136, 308350, 538807, 250884, 225609, 876945,
       461307, 559545, 129847, 246695, 611088, 305201, 415165, 961630,
       852593, 365803, 464443, 447409, 781295, 544287, 409990, 962828,
       506159, 710401, 422181, 226281, 801730, 616855, 214035, 592522,
       790224, 313276, 195261, 709870, 309723, 448827, 252094, 246354,
       267421, 236022, 604103, 570562, 541139, 159524, 642551, 496245,
       488686, 308261, 161282, 402257, 508477, 750007, 853337, 340628,
       139165, 603606, 920730, 432151, 328932, 907980, 135799, 605199,
       667535, 965225, 643243, 762475, 428029, 735569, 438097, 422797,
       989925, 535872, 127526, 322524, 563126, 937729, 271583, 938207,
       227789, 128904, 412120, 293848, 322481, 206353, 954858, 845205,
       310436, 861142, 984841, 723509, 410905, 799995, 887054, 535320,
       867708, 392488, 487190, 329028, 192569, 705848, 145463, 223805,
       263840, 668014, 526077, 316258, 239792, 577363, 890075, 792079,
       311328, 416106, 525962, 856249, 628401, 199299, 585491, 111225,
       873676, 823235, 426750, 750976, 238069, 836235, 224851, 557203,
       975546, 147500, 787074, 699892, 712951, 291700, 156073, 816974,
       959470, 562066, 700773, 832534, 152908, 863289, 380329, 949516,
       638844, 834410, 276769, 546504, 742987, 626107, 335377, 350138,
       393377, 396206, 585716, 745370, 423690, 657550, 492402, 437836,
       588197, 843118, 427115, 230929, 671848, 629491, 606223, 936761,
       952620, 644035, 486445, 955456, 551659, 672788, 264621, 768193,
       773579, 109474, 360627, 825744, 348774, 523337, 215010, 924328,
       153861, 955500, 449016, 880860, 298448, 515651, 241578, 654116,
       924599, 966335, 412207, 754755, 144368, 415584, 692862, 894674,
       778249, 146690, 461404, 905863, 335609, 401114, 239876, 820493,
       710249, 723591, 744400, 384924, 622986, 748665, 396897, 444591,
       398008, 604104, 238688, 145494, 866850, 144903, 115217, 938533,
       155428, 179548, 207348, 308275, 491615, 901895, 724062, 820634,
       252369, 333344, 174000, 871419, 160097, 501173, 726216, 451702,
       392531, 415747, 187047, 573482, 792550, 922924, 268369, 141969,
       453623, 209337, 898814, 336605, 715508, 794045, 832595, 168949,
       769384, 107362, 661627, 922770, 336100, 343708, 156718, 881913,
       850861, 665646, 433922, 391144, 521989, 383206, 171313, 120068,
       774201, 469130, 750250, 368103, 684613, 188674, 773231, 686990,
       804037, 211882, 751653, 970292, 220423, 500903, 488778, 499765,
       123475, 826781, 168018, 148052, 976126, 587607, 315138, 722545,
       936140, 900294, 405317, 659915, 785828, 832730, 800915, 825598,
       888669, 966860, 989156, 693537, 702628, 884821, 192015, 724508,
       434022, 191660, 638335, 728884, 232219, 702049, 630552, 415038,
       983790, 428112, 402175, 122500, 416355, 811437, 969365, 877142,
       566629, 240149, 834961, 530280, 138810, 805201, 864996, 885160,
       862870, 793748, 433743, 505708, 505852, 179134, 846798, 798991,
       879062, 171701, 874205, 342508, 543513, 252886, 167079, 264200,
       955356, 976874, 462550, 961633, 800787, 152462, 704980, 523681,
       952108, 877845, 627399, 709933, 282301, 537605, 255774, 847614,
       411022, 705456, 325835, 487018, 888879, 858082, 595526, 683331,
       848260, 648494, 191065, 998075, 728808, 782403, 772359, 673696,
       576443, 251664, 886571, 752713, 994488, 809627, 873040, 728969,
       313346, 576952, 649450, 404016, 518145, 226251, 376046, 640239,
       123825, 845682, 110985, 740326, 845952, 314878, 217655, 228029,
       889425, 431042, 997455, 307407, 693022, 354479, 752643, 586199,
       230533, 241883, 228857, 770405, 184631, 583265, 931613, 926716,
       296160, 959524, 523736, 581985, 160308, 330981, 916739, 499012,
       857972, 545455, 381440, 645000, 752486, 178600, 465810, 959194,
       236848, 270327, 978720, 631746, 367046, 411219, 182832, 224285,
       487524, 609293, 914021, 155991, 593283, 680428, 156204, 140250,
       427414, 356409, 640992, 574201, 565676, 892382, 572753, 817893,
       513993, 322147, 523053, 780320, 622150, 502414, 578540, 489950,
       726372, 655173, 580492, 733854, 218690, 283549, 824489, 170350,
       922964, 787783, 620465, 445461, 488219, 761323, 123948, 824808,
       626405, 651380, 684473, 910019, 783418, 825325, 958602, 724787,
       772796, 572274, 567686, 573943, 544645, 183095, 563693, 828980,
       689124, 552131, 415356, 556714, 309920, 563567, 155692, 588781,
       411359, 501750, 704520, 471741, 211971, 248073, 398358, 969225,
       256361, 298549, 718310, 189503, 802893, 517861, 346671, 153793,
       253968, 192976, 618123, 312682, 101121, 767537, 763409, 179336,
       932353, 147633, 969418, 269358, 519246, 977690, 236356, 111542,
       486559, 753289, 112606, 121534, 424495, 539118, 200128, 664012,
       611136, 758042, 875828, 520212, 371494, 812551, 429092, 997311,
       916379, 596553, 107596, 913119, 539984, 840047, 788779, 453383,
       407424, 484987, 261163, 644773, 366958, 232415, 965730, 473040,
       235221, 385426, 919734, 825136, 972693, 775945, 639396, 615378,
       304562, 478413, 839887, 939184, 156182, 725156, 884767, 290159,
       139956, 146416, 484617, 436199, 956141, 385919, 223340, 765478,
       658182, 570919, 209833, 374340, 533705, 575048, 768884, 267448,
       987963, 550978, 508438, 320315, 486696, 615977, 267483, 605624,
       236169, 616393, 372355, 478348, 431361, 967264, 388350, 481616,
       786691, 349496, 631483, 829512, 789352, 704606, 272533, 509080,
       545813, 848254, 362685, 997461, 588613, 613562, 845320, 366960,
       668497, 717854, 217003, 700328, 801495, 657944, 669026, 206751,
       249334, 765414, 355069, 644548, 941845, 797010, 344814, 161950,
       310010, 166206, 760107, 122034, 154834, 730923, 362993, 755087,
       936629, 251528, 152984, 209935, 901862, 299843, 638429, 283799,
       589685, 166566, 104392, 607169, 850361, 766646, 724940, 401921,
       687324, 261901, 319791, 897035, 659773, 439645, 702990, 261620,
       352665, 936568, 316745, 196714, 331581, 324966, 372734, 732325,
       191709, 577868, 390855, 155723, 445975, 529466, 856079, 915188,
       817397, 215941, 552271, 260836, 363281, 191833, 223599, 256512,
       617914, 156824, 306429, 572565, 375322, 846513, 489517, 729677,
       988625, 251339, 424766, 329087, 206319, 861132, 624248, 729088,
       907599, 791092, 919036, 348817, 995746, 203940, 788266, 597504,
       258912, 707179, 660121, 448870, 634931, 931980, 558553, 204392,
       191516, 173914, 189781, 841249, 236237, 104650, 806848, 970366,
       453622, 404927, 428499, 189379, 730002, 277478, 837297, 409113,
       738441, 492338, 216897, 225128, 297531, 388884, 232406, 803877,
       232473, 694141, 413778, 814625, 588666, 605206, 271067, 972388,
       384026, 662486, 980180, 323121, 991411, 417152, 622674, 803708,
       625434, 942008, 284418, 799857, 116394, 457878, 236903, 991023,
       543110, 704252, 400457, 733690, 927394, 954433, 414367, 199387,
       242777, 638369, 404872, 193856, 725118, 328223, 418190, 163370,
       612158, 984941, 753571, 316552, 148198, 877600, 709978, 545238,
       613484, 295613, 447016, 736870, 437459, 239071, 831315, 720984,
       484006, 245851, 200795, 525081, 868062, 790542, 416613, 795940,
       272258, 139091, 515655, 300327, 806762, 652278, 870720, 582444,
       919274, 256007, 445597, 228961, 145974, 363571, 408759, 971280])

Task 116: Generate 50 equally spaced price points between £0 and £500.

In [261]:
price_points = np.linspace(0, 500, 50)

In [262]:
price_points

array([  0.        ,  10.20408163,  20.40816327,  30.6122449 ,
        40.81632653,  51.02040816,  61.2244898 ,  71.42857143,
        81.63265306,  91.83673469, 102.04081633, 112.24489796,
       122.44897959, 132.65306122, 142.85714286, 153.06122449,
       163.26530612, 173.46938776, 183.67346939, 193.87755102,
       204.08163265, 214.28571429, 224.48979592, 234.69387755,
       244.89795918, 255.10204082, 265.30612245, 275.51020408,
       285.71428571, 295.91836735, 306.12244898, 316.32653061,
       326.53061224, 336.73469388, 346.93877551, 357.14285714,
       367.34693878, 377.55102041, 387.75510204, 397.95918367,
       408.16326531, 418.36734694, 428.57142857, 438.7755102 ,
       448.97959184, 459.18367347, 469.3877551 , 479.59183673,
       489.79591837, 500.        ])

Task 117: Create a matrix representing 12 months and 7 product categories filled with zeros.

In [263]:
matrix = np.zeros((12, 7))

In [264]:
matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Task 118: Extract quantities greater than 100 from the Quantity array.

In [265]:
large_quantities = df['Quantity'][df['Quantity'] > 100].to_numpy()

In [266]:
large_quantities

array([120, 192, 192, ..., 180, 144, 144])

Task 119: Calculate the square root of all UnitPrice values.

In [267]:
unitprice_sqrt = np.sqrt(df['UnitPrice'].to_numpy())

In [268]:
unitprice_sqrt

array([1.59687194, 1.84119526, 1.6583124 , ..., 2.03715488, 2.03715488,
       2.22485955])

Task 120: Find the 25th, 50th, and 75th percentiles of TotalPrice.

In [269]:
percentiles = np.percentile(df['TotalPrice'], [25, 50, 75])

In [270]:
percentiles

array([ 4.25, 11.7 , 19.8 ])

Task 121: Round all UnitPrice values to the nearest integer.

In [271]:
df['UnitPriceRounded'] = df['UnitPrice'].round(0).astype(int)

In [272]:
df['UnitPriceRounded']

0         3
1         3
2         3
3         3
4         3
         ..
401599    1
401600    2
401601    4
401602    4
401603    5
Name: UnitPriceRounded, Length: 401604, dtype: int64

Task 122: Find positions where Quantity is maximum.

In [273]:
max_qty_positions = np.where(df['Quantity'] == df['Quantity'].max())[0]

In [274]:
max_qty_positions

array([401131])

Task 123: Calculate the correlation between Quantity and UnitPrice.

In [275]:
correlation = df['Quantity'].corr(df['UnitPrice'])

In [276]:
correlation

np.float64(-0.0012434674782030096)

Task 124: Normalize the TotalPrice column (subtract mean, divide by standard deviation).

In [277]:
df['TotalPriceNormalized'] = (df['TotalPrice'] - df['TotalPrice'].mean()) / df['TotalPrice'].std()

In [278]:
df['TotalPriceNormalized']

0        -0.012347
1        -0.000636
2         0.003221
3        -0.000636
4        -0.000636
            ...
401599   -0.024198
401600   -0.018621
401601   -0.009326
401602   -0.009326
401603   -0.013393
Name: TotalPriceNormalized, Length: 401604, dtype: float64

Task 125: Split the Quantity array into 4 equal parts.

In [279]:
quantity_parts = np.array_split(df['Quantity'].to_numpy(), 4)

In [280]:
quantity_parts

[array([6, 6, 8, ..., 3, 3, 5]),
 array([ 4,  3,  1, ..., 12,  6,  1]),
 array([ 6, 12,  4, ...,  4,  4,  6]),
 array([ 4, 10, 32, ...,  4,  4,  3])]

**PART S: Export and Documentation**

Task 126: Save your cleaned dataset to a CSV file.

In [281]:
import numpy as np
import pandas as pd

In [282]:
clean_df = df.to_csv('cleaned_online_retail.csv', index=False)

In [283]:
df_1 = pd.read_csv('/content/cleaned_online_retail.csv')

In [284]:
df_1

,InvoiceNo,StockCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,...,Qurater,RevenueCategory,OrderSize,Length_product_name,Counrty,MonthlyRevenuePct,CustomerRank,CumulativeRevenue,UnitPriceRounded,TotalPriceNormalized
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,UK,15.30,2010,...,2010Q4,Medium,Medium,34,United Kingdom,0.002770,240.0,1.530000e+01,3,-0.012347
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,2010Q4,Medium,Medium,19,United Kingdom,0.003682,240.0,3.564000e+01,3,-0.000636
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,UK,22.00,2010,...,2010Q4,Medium,Medium,30,United Kingdom,0.003983,240.0,5.764000e+01,3,0.003221
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,2010Q4,Medium,Medium,35,United Kingdom,0.003682,240.0,7.798000e+01,3,-0.000636
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,UK,20.34,2010,...,2010Q4,Medium,Medium,30,United Kingdom,0.003682,240.0,9.832000e+01,3,-0.000636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,2011,...,2011Q4,Medium,Medium,27,France,0.002986,1796.0,8.278333e+06,1,-0.024198
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,2011,...,2011Q4,Medium,Medium,28,France,0.003689,1796.0,8.278323e+06,2,-0.018621
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,2011Q4,Medium,Small,29,France,0.004860,1796.0,8.278287e+06,4,-0.009326
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,2011,...,2011Q4,Medium,Small,31,France,0.004860,1796.0,8.278490e+06,4,-0.009326
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,2011,...,2011Q4,Medium,Small,29,France,0.004348,1796.0,8.278519e+06,5,-0.013393

Task 127: Save your cleaned dataset to an Excel file.

In [285]:
df.to_excel('cleaned_online_retail.xlsx', index=False)

Task 128: Create an Excel file with multiple sheets:

Sheet 1: Full cleaned data

Sheet 2: Country-wise summary

Sheet 3: Monthly revenue trends

Sheet 4: Top 50 customers

In [289]:
with pd.ExcelWriter('online_retail_report.xlsx') as writer:
    df.to_excel(writer, sheet_name='Full_Cleaned_Data', index=False)
    df.groupby('Country')['TotalPrice'].sum().to_excel(writer, sheet_name='Country_Wise_Revenue')
    df.groupby(df['InvoiceDate'].dt.to_period('M'))['TotalPrice'].sum().to_excel(writer, sheet_name='Monthly_Revenue')
    df.groupby('CustomerID')['TotalPrice'].sum().sort_values(ascending=False).head(50).to_excel(writer, sheet_name='Top_50_Customers')

Task 129: Export the pivot table from Task 100 to Excel.

In [295]:
monthly_sales_country.to_excel('task_129_monthly_sales_country.xlsx',index=False)

In [296]:
monthly_sales_country

InvoiceDate,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12
Country,,,,,,,,,,,,,
Australia,937.60,9017.71,14627.47,17055.29,333.400,13628.51,25164.77,4767.570,22489.20,5031.730,17150.53,6805.99,0.00
Austria,257.04,0.00,518.36,1708.12,680.780,1249.43,-24.20,1191.950,1516.08,0.000,1043.78,1329.78,683.20
Bahrain,0.00,0.00,0.00,0.00,0.000,548.40,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Belgium,1809.91,1154.05,2161.32,3333.58,1954.150,2727.00,4273.17,2473.620,3536.12,4197.820,5651.38,6229.41,1409.43
Brazil,0.00,0.00,0.00,0.00,1143.600,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Canada,0.00,0.00,0.00,140.54,0.000,534.24,1171.46,1768.580,51.56,0.000,0.00,0.00,0.00
Channel Islands,363.53,645.08,1784.71,3509.33,293.000,903.79,2060.03,0.000,4882.63,1321.650,2623.32,1495.17,194.15
Cyprus,1587.07,547.50,4013.55,938.39,-35.800,0.00,1109.32,0.000,0.00,196.350,4153.97,439.66,-91.25
Czech Republic,0.00,0.00,549.26,0.00,-57.510,0.00,0.00,0.000,0.00,0.000,277.48,-61.51,0.00
Denmark,1281.50,0.00,399.22,3978.99,0.000,515.70,3261.15,376.240,78.60,4570.160,1438.11,2699.57,168.90
European Community,0.00,0.00,0.00,0.00,191.400,0.00,423.55,676.800,0.00,0.000,0.00,0.00,0.00
Finland,892.80,889.02,205.16,5924.62,1626.810,0.00,329.56,2996.730,1371.55,1105.450,2804.12,2950.24,1230.68
France,9575.36,17503.07,8438.91,14512.30,4195.210,17518.68,15722.43,9888.990,13789.26,23198.870,25017.64,30216.50,7048.83
Germany,14527.44,16421.43,8969.24,14170.02,11963.370,25554.85,13053.27,15721.660,19023.65,17708.560,30604.27,25987.01,7804.70
Greece,0.00,2661.24,0.00,387.31,609.740,0.00,0.00,371.240,0.00,0.000,0.00,0.00,680.99
Iceland,711.79,475.39,0.00,0.00,636.250,0.00,382.52,0.000,584.91,0.000,1294.32,0.00,224.82
Ireland,7825.57,21671.52,7536.92,18270.28,7570.500,15889.74,19822.79,40823.150,10771.45,40427.840,23292.62,29123.03,6976.37
Israel,-227.44,0.00,779.10,0.00,0.000,0.00,0.00,1430.750,4873.81,0.000,132.18,0.00,0.00
Italy,794.50,2361.36,251.50,1778.91,737.830,587.45,162.27,147.100,1934.80,279.800,3410.79,4243.75,200.45
Japan,7705.07,-109.80,5780.81,-73.66,4871.830,1351.45,1607.04,3854.400,-49.79,112.080,1948.04,8460.08,-116.93
Lebanon,0.00,1693.88,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Lithuania,1661.06,0.00,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Malta,0.00,0.00,0.00,0.00,0.000,0.00,850.41,0.000,1103.25,0.000,0.00,582.62,-30.81
Netherlands,8784.48,26611.16,22932.11,22416.49,2976.560,29185.88,26843.09,26.020,39655.81,26937.260,40708.65,25856.01,11728.02
Norway,3787.12,0.00,630.90,304.68,0.000,0.00,5886.86,890.070,1984.46,8678.940,3687.23,6527.50,2785.70
Poland,248.16,613.22,604.05,303.39,705.840,1522.37,264.74,678.450,401.80,529.250,0.00,1341.87,0.00
Portugal,2380.12,3998.11,1213.90,2660.85,1687.750,587.83,879.51,2287.850,1206.40,1433.220,5254.97,2603.30,2801.95
RSA,0.00,0.00,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.000,1002.31,0.00,0.00
Saudi Arabia,0.00,0.00,145.92,-14.75,0.000,0.00,0.00,0.000,0.00,0.000,0.00,0.00,0.00
Singapore,0.00,2053.07,0.00,0.00,2118.740,0.00,0.00,3949.320,0.00,0.000,999.26,0.00,0.00
Spain,1843.73,7178.54,2093.70,5326.65,1785.650,3257.60,3332.44,7574.020,3325.91,5163.740,5078.65,8523.97,271.43
Sweden,2646.30,3446.32,509.50,4540.58,809.100,2664.98,832.00,6802.090,1380.46,4575.210,5766.16,2612.71,0.00
Switzerland,1304.92,4231.23,2642.67,1870.23,1822.190,3567.21,7882.20,3540.650,4882.19,8254.960,7623.99,8116.96,0.00
UK,481675.23,350668.80,347856.55,455534.07,375919.231,524363.88,471386.36,460082.891,475752.95,774620.302,781610.92,950731.45,296953.52
USA,0.00,0.00,0.00,0.00,383.950,0.00,0.00,0.000,0.00,0.000,731.69,0.00,615.28
United Arab Emirates,0.00,0.00,889.24,0.00,0.000,0.00,0.00,0.000,0.00,1013.040,0.00,0.00,0.00
Unspecified,0.00,0.00,0.00,0.00,299.100,852.68,185.78,792.180,531.03,0.000,0.00,0.00,0.00

Task 130: Create a text file documenting all the insights you discovered from this analysis.

In [297]:
insights_text = """
E-COMMERCE ANALYSIS INSIGHTS
----------------------------
1. Revenue is heavily concentrated in the UK.
2. Q4 shows significant seasonality peaks.
3. A small percentage of customers drive the majority of revenue (Pareto Principle).
4. Cancellations (Invoice 'C') were significant before cleaning.
"""

with open('Analysis_Insights.txt', 'w') as f:
    f.write(insights_text)

print("Export protocols initiated. Files generated successfully.")

Export protocols initiated. Files generated successfully.